// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/type/fraction.proto

#include "google/type/fraction.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace google {
namespace type {
PROTOBUF_CONSTEXPR Fraction::Fraction(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.numerator_)*/int64_t{0}
  , /*decltype(_impl_.denominator_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FractionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FractionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FractionDefaultTypeInternal() {}
  union {
    Fraction _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FractionDefaultTypeInternal _Fraction_default_instance_;
}  // namespace type
}  // namespace google
static ::_pb::Metadata file_level_metadata_google_2ftype_2ffraction_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_google_2ftype_2ffraction_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_google_2ftype_2ffraction_2eproto = nullptr;

const uint32_t TableStruct_google_2ftype_2ffraction_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::type::Fraction, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::type::Fraction, _impl_.numerator_),
  PROTOBUF_FIELD_OFFSET(::google::type::Fraction, _impl_.denominator_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::google::type::Fraction)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::google::type::_Fraction_default_instance_._instance,
};

const char descriptor_table_protodef_google_2ftype_2ffraction_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032google/type/fraction.proto\022\013google.typ"
  "e\"J\n\010Fraction\022\034\n\tnumerator\030\001 \001(\003R\tnumera"
  "tor\022 \n\013denominator\030\002 \001(\003R\013denominatorB\253\001"
  "\n\017com.google.typeB\rFractionProtoP\001Z<goog"
  "le.golang.org/genproto/googleapis/type/f"
  "raction;fraction\242\002\003GTX\252\002\013Google.Type\312\002\013G"
  "oogle\\Type\342\002\027Google\\Type\\GPBMetadata\352\002\014G"
  "oogle::Typeb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_google_2ftype_2ffraction_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_google_2ftype_2ffraction_2eproto = {
    false, false, 299, descriptor_table_protodef_google_2ftype_2ffraction_2eproto,
    "google/type/fraction.proto",
    &descriptor_table_google_2ftype_2ffraction_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_google_2ftype_2ffraction_2eproto::offsets,
    file_level_metadata_google_2ftype_2ffraction_2eproto, file_level_enum_descriptors_google_2ftype_2ffraction_2eproto,
    file_level_service_descriptors_google_2ftype_2ffraction_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_google_2ftype_2ffraction_2eproto_getter() {
  return &descriptor_table_google_2ftype_2ffraction_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_google_2ftype_2ffraction_2eproto(&descriptor_table_google_2ftype_2ffraction_2eproto);
namespace google {
namespace type {

// ===================================================================

class Fraction::_Internal {
 public:
};

Fraction::Fraction(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.type.Fraction)
}
Fraction::Fraction(const Fraction& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Fraction* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.numerator_){}
    , decltype(_impl_.denominator_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.numerator_, &from._impl_.numerator_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.denominator_) -
    reinterpret_cast<char*>(&_impl_.numerator_)) + sizeof(_impl_.denominator_));
  // @@protoc_insertion_point(copy_constructor:google.type.Fraction)
}

inline void Fraction::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.numerator_){int64_t{0}}
    , decltype(_impl_.denominator_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Fraction::~Fraction() {
  // @@protoc_insertion_point(destructor:google.type.Fraction)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Fraction::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Fraction::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Fraction::Clear() {
// @@protoc_insertion_point(message_clear_start:google.type.Fraction)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.numerator_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.denominator_) -
      reinterpret_cast<char*>(&_impl_.numerator_)) + sizeof(_impl_.denominator_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Fraction::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 numerator = 1 [json_name = "numerator"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.numerator_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 denominator = 2 [json_name = "denominator"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.denominator_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Fraction::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.type.Fraction)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 numerator = 1 [json_name = "numerator"];
  if (this->_internal_numerator() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_numerator(), target);
  }

  // int64 denominator = 2 [json_name = "denominator"];
  if (this->_internal_denominator() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_denominator(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.type.Fraction)
  return target;
}

size_t Fraction::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.type.Fraction)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 numerator = 1 [json_name = "numerator"];
  if (this->_internal_numerator() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_numerator());
  }

  // int64 denominator = 2 [json_name = "denominator"];
  if (this->_internal_denominator() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_denominator());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Fraction::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Fraction::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Fraction::GetClassData() const { return &_class_data_; }


void Fraction::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Fraction*>(&to_msg);
  auto& from = static_cast<const Fraction&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.type.Fraction)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_numerator() != 0) {
    _this->_internal_set_numerator(from._internal_numerator());
  }
  if (from._internal_denominator() != 0) {
    _this->_internal_set_denominator(from._internal_denominator());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Fraction::CopyFrom(const Fraction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.type.Fraction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Fraction::IsInitialized() const {
  return true;
}

void Fraction::InternalSwap(Fraction* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Fraction, _impl_.denominator_)
      + sizeof(Fraction::_impl_.denominator_)
      - PROTOBUF_FIELD_OFFSET(Fraction, _impl_.numerator_)>(
          reinterpret_cast<char*>(&_impl_.numerator_),
          reinterpret_cast<char*>(&other->_impl_.numerator_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Fraction::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2ftype_2ffraction_2eproto_getter, &descriptor_table_google_2ftype_2ffraction_2eproto_once,
      file_level_metadata_google_2ftype_2ffraction_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace type
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::google::type::Fraction*
Arena::CreateMaybeMessage< ::google::type::Fraction >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::type::Fraction >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
