// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/type/localized_text.proto

#include "google/type/localized_text.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace google {
namespace type {
PROTOBUF_CONSTEXPR LocalizedText::LocalizedText(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.text_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.language_code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LocalizedTextDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LocalizedTextDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LocalizedTextDefaultTypeInternal() {}
  union {
    LocalizedText _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LocalizedTextDefaultTypeInternal _LocalizedText_default_instance_;
}  // namespace type
}  // namespace google
static ::_pb::Metadata file_level_metadata_google_2ftype_2flocalized_5ftext_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_google_2ftype_2flocalized_5ftext_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_google_2ftype_2flocalized_5ftext_2eproto = nullptr;

const uint32_t TableStruct_google_2ftype_2flocalized_5ftext_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::type::LocalizedText, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::type::LocalizedText, _impl_.text_),
  PROTOBUF_FIELD_OFFSET(::google::type::LocalizedText, _impl_.language_code_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::google::type::LocalizedText)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::google::type::_LocalizedText_default_instance_._instance,
};

const char descriptor_table_protodef_google_2ftype_2flocalized_5ftext_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n google/type/localized_text.proto\022\013goog"
  "le.type\"H\n\rLocalizedText\022\022\n\004text\030\001 \001(\tR\004"
  "text\022#\n\rlanguage_code\030\002 \001(\tR\014languageCod"
  "eB\277\001\n\017com.google.typeB\022LocalizedTextProt"
  "oP\001ZHgoogle.golang.org/genproto/googleap"
  "is/type/localized_text;localized_text\370\001\001"
  "\242\002\003GTX\252\002\013Google.Type\312\002\013Google\\Type\342\002\027Goo"
  "gle\\Type\\GPBMetadata\352\002\014Google::Typeb\006pro"
  "to3"
  ;
static ::_pbi::once_flag descriptor_table_google_2ftype_2flocalized_5ftext_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_google_2ftype_2flocalized_5ftext_2eproto = {
    false, false, 323, descriptor_table_protodef_google_2ftype_2flocalized_5ftext_2eproto,
    "google/type/localized_text.proto",
    &descriptor_table_google_2ftype_2flocalized_5ftext_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_google_2ftype_2flocalized_5ftext_2eproto::offsets,
    file_level_metadata_google_2ftype_2flocalized_5ftext_2eproto, file_level_enum_descriptors_google_2ftype_2flocalized_5ftext_2eproto,
    file_level_service_descriptors_google_2ftype_2flocalized_5ftext_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_google_2ftype_2flocalized_5ftext_2eproto_getter() {
  return &descriptor_table_google_2ftype_2flocalized_5ftext_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_google_2ftype_2flocalized_5ftext_2eproto(&descriptor_table_google_2ftype_2flocalized_5ftext_2eproto);
namespace google {
namespace type {

// ===================================================================

class LocalizedText::_Internal {
 public:
};

LocalizedText::LocalizedText(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.type.LocalizedText)
}
LocalizedText::LocalizedText(const LocalizedText& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LocalizedText* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.text_){}
    , decltype(_impl_.language_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_text().empty()) {
    _this->_impl_.text_.Set(from._internal_text(), 
      _this->GetArenaForAllocation());
  }
  _impl_.language_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.language_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_language_code().empty()) {
    _this->_impl_.language_code_.Set(from._internal_language_code(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:google.type.LocalizedText)
}

inline void LocalizedText::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.text_){}
    , decltype(_impl_.language_code_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.language_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.language_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LocalizedText::~LocalizedText() {
  // @@protoc_insertion_point(destructor:google.type.LocalizedText)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LocalizedText::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.text_.Destroy();
  _impl_.language_code_.Destroy();
}

void LocalizedText::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LocalizedText::Clear() {
// @@protoc_insertion_point(message_clear_start:google.type.LocalizedText)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.text_.ClearToEmpty();
  _impl_.language_code_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LocalizedText::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string text = 1 [json_name = "text"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_text();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "google.type.LocalizedText.text"));
        } else
          goto handle_unusual;
        continue;
      // string language_code = 2 [json_name = "languageCode"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_language_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "google.type.LocalizedText.language_code"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LocalizedText::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.type.LocalizedText)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string text = 1 [json_name = "text"];
  if (!this->_internal_text().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_text().data(), static_cast<int>(this->_internal_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.type.LocalizedText.text");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_text(), target);
  }

  // string language_code = 2 [json_name = "languageCode"];
  if (!this->_internal_language_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_language_code().data(), static_cast<int>(this->_internal_language_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.type.LocalizedText.language_code");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_language_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.type.LocalizedText)
  return target;
}

size_t LocalizedText::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.type.LocalizedText)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string text = 1 [json_name = "text"];
  if (!this->_internal_text().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_text());
  }

  // string language_code = 2 [json_name = "languageCode"];
  if (!this->_internal_language_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_language_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LocalizedText::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LocalizedText::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LocalizedText::GetClassData() const { return &_class_data_; }


void LocalizedText::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LocalizedText*>(&to_msg);
  auto& from = static_cast<const LocalizedText&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.type.LocalizedText)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  if (!from._internal_language_code().empty()) {
    _this->_internal_set_language_code(from._internal_language_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LocalizedText::CopyFrom(const LocalizedText& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.type.LocalizedText)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LocalizedText::IsInitialized() const {
  return true;
}

void LocalizedText::InternalSwap(LocalizedText* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.text_, lhs_arena,
      &other->_impl_.text_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.language_code_, lhs_arena,
      &other->_impl_.language_code_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata LocalizedText::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2ftype_2flocalized_5ftext_2eproto_getter, &descriptor_table_google_2ftype_2flocalized_5ftext_2eproto_once,
      file_level_metadata_google_2ftype_2flocalized_5ftext_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace type
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::google::type::LocalizedText*
Arena::CreateMaybeMessage< ::google::type::LocalizedText >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::type::LocalizedText >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
