// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/type/month.proto

#include "google/type/month.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace google {
namespace type {
}  // namespace type
}  // namespace google
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_google_2ftype_2fmonth_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_google_2ftype_2fmonth_2eproto = nullptr;
const uint32_t TableStruct_google_2ftype_2fmonth_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_google_2ftype_2fmonth_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027google/type/month.proto\022\013google.type*\260"
  "\001\n\005Month\022\025\n\021MONTH_UNSPECIFIED\020\000\022\013\n\007JANUA"
  "RY\020\001\022\014\n\010FEBRUARY\020\002\022\t\n\005MARCH\020\003\022\t\n\005APRIL\020\004"
  "\022\007\n\003MAY\020\005\022\010\n\004JUNE\020\006\022\010\n\004JULY\020\007\022\n\n\006AUGUST\020"
  "\010\022\r\n\tSEPTEMBER\020\t\022\013\n\007OCTOBER\020\n\022\014\n\010NOVEMBE"
  "R\020\013\022\014\n\010DECEMBER\020\014B\242\001\n\017com.google.typeB\nM"
  "onthProtoP\001Z6google.golang.org/genproto/"
  "googleapis/type/month;month\242\002\003GTX\252\002\013Goog"
  "le.Type\312\002\013Google\\Type\342\002\027Google\\Type\\GPBM"
  "etadata\352\002\014Google::Typeb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_google_2ftype_2fmonth_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_google_2ftype_2fmonth_2eproto = {
    false, false, 390, descriptor_table_protodef_google_2ftype_2fmonth_2eproto,
    "google/type/month.proto",
    &descriptor_table_google_2ftype_2fmonth_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_google_2ftype_2fmonth_2eproto::offsets,
    nullptr, file_level_enum_descriptors_google_2ftype_2fmonth_2eproto,
    file_level_service_descriptors_google_2ftype_2fmonth_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_google_2ftype_2fmonth_2eproto_getter() {
  return &descriptor_table_google_2ftype_2fmonth_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_google_2ftype_2fmonth_2eproto(&descriptor_table_google_2ftype_2fmonth_2eproto);
namespace google {
namespace type {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Month_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_google_2ftype_2fmonth_2eproto);
  return file_level_enum_descriptors_google_2ftype_2fmonth_2eproto[0];
}
bool Month_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace type
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
