// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/type/postal_address.proto

#include "google/type/postal_address.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace google {
namespace type {
PROTOBUF_CONSTEXPR PostalAddress::PostalAddress(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.address_lines_)*/{}
  , /*decltype(_impl_.recipients_)*/{}
  , /*decltype(_impl_.region_code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.language_code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.postal_code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sorting_code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.administrative_area_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.locality_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sublocality_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.organization_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.revision_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PostalAddressDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PostalAddressDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PostalAddressDefaultTypeInternal() {}
  union {
    PostalAddress _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PostalAddressDefaultTypeInternal _PostalAddress_default_instance_;
}  // namespace type
}  // namespace google
static ::_pb::Metadata file_level_metadata_google_2ftype_2fpostal_5faddress_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_google_2ftype_2fpostal_5faddress_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_google_2ftype_2fpostal_5faddress_2eproto = nullptr;

const uint32_t TableStruct_google_2ftype_2fpostal_5faddress_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::type::PostalAddress, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::type::PostalAddress, _impl_.revision_),
  PROTOBUF_FIELD_OFFSET(::google::type::PostalAddress, _impl_.region_code_),
  PROTOBUF_FIELD_OFFSET(::google::type::PostalAddress, _impl_.language_code_),
  PROTOBUF_FIELD_OFFSET(::google::type::PostalAddress, _impl_.postal_code_),
  PROTOBUF_FIELD_OFFSET(::google::type::PostalAddress, _impl_.sorting_code_),
  PROTOBUF_FIELD_OFFSET(::google::type::PostalAddress, _impl_.administrative_area_),
  PROTOBUF_FIELD_OFFSET(::google::type::PostalAddress, _impl_.locality_),
  PROTOBUF_FIELD_OFFSET(::google::type::PostalAddress, _impl_.sublocality_),
  PROTOBUF_FIELD_OFFSET(::google::type::PostalAddress, _impl_.address_lines_),
  PROTOBUF_FIELD_OFFSET(::google::type::PostalAddress, _impl_.recipients_),
  PROTOBUF_FIELD_OFFSET(::google::type::PostalAddress, _impl_.organization_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::google::type::PostalAddress)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::google::type::_PostalAddress_default_instance_._instance,
};

const char descriptor_table_protodef_google_2ftype_2fpostal_5faddress_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n google/type/postal_address.proto\022\013goog"
  "le.type\"\215\003\n\rPostalAddress\022\032\n\010revision\030\001 "
  "\001(\005R\010revision\022\037\n\013region_code\030\002 \001(\tR\nregi"
  "onCode\022#\n\rlanguage_code\030\003 \001(\tR\014languageC"
  "ode\022\037\n\013postal_code\030\004 \001(\tR\npostalCode\022!\n\014"
  "sorting_code\030\005 \001(\tR\013sortingCode\022/\n\023admin"
  "istrative_area\030\006 \001(\tR\022administrativeArea"
  "\022\032\n\010locality\030\007 \001(\tR\010locality\022 \n\013sublocal"
  "ity\030\010 \001(\tR\013sublocality\022#\n\raddress_lines\030"
  "\t \003(\tR\014addressLines\022\036\n\nrecipients\030\n \003(\tR"
  "\nrecipients\022\"\n\014organization\030\013 \001(\tR\014organ"
  "izationB\275\001\n\017com.google.typeB\022PostalAddre"
  "ssProtoP\001ZFgoogle.golang.org/genproto/go"
  "ogleapis/type/postaladdress;postaladdres"
  "s\370\001\001\242\002\003GTX\252\002\013Google.Type\312\002\013Google\\Type\342\002"
  "\027Google\\Type\\GPBMetadata\352\002\014Google::Typeb"
  "\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_google_2ftype_2fpostal_5faddress_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_google_2ftype_2fpostal_5faddress_2eproto = {
    false, false, 647, descriptor_table_protodef_google_2ftype_2fpostal_5faddress_2eproto,
    "google/type/postal_address.proto",
    &descriptor_table_google_2ftype_2fpostal_5faddress_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_google_2ftype_2fpostal_5faddress_2eproto::offsets,
    file_level_metadata_google_2ftype_2fpostal_5faddress_2eproto, file_level_enum_descriptors_google_2ftype_2fpostal_5faddress_2eproto,
    file_level_service_descriptors_google_2ftype_2fpostal_5faddress_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_google_2ftype_2fpostal_5faddress_2eproto_getter() {
  return &descriptor_table_google_2ftype_2fpostal_5faddress_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_google_2ftype_2fpostal_5faddress_2eproto(&descriptor_table_google_2ftype_2fpostal_5faddress_2eproto);
namespace google {
namespace type {

// ===================================================================

class PostalAddress::_Internal {
 public:
};

PostalAddress::PostalAddress(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.type.PostalAddress)
}
PostalAddress::PostalAddress(const PostalAddress& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PostalAddress* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.address_lines_){from._impl_.address_lines_}
    , decltype(_impl_.recipients_){from._impl_.recipients_}
    , decltype(_impl_.region_code_){}
    , decltype(_impl_.language_code_){}
    , decltype(_impl_.postal_code_){}
    , decltype(_impl_.sorting_code_){}
    , decltype(_impl_.administrative_area_){}
    , decltype(_impl_.locality_){}
    , decltype(_impl_.sublocality_){}
    , decltype(_impl_.organization_){}
    , decltype(_impl_.revision_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.region_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.region_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_region_code().empty()) {
    _this->_impl_.region_code_.Set(from._internal_region_code(), 
      _this->GetArenaForAllocation());
  }
  _impl_.language_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.language_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_language_code().empty()) {
    _this->_impl_.language_code_.Set(from._internal_language_code(), 
      _this->GetArenaForAllocation());
  }
  _impl_.postal_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.postal_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_postal_code().empty()) {
    _this->_impl_.postal_code_.Set(from._internal_postal_code(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sorting_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sorting_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sorting_code().empty()) {
    _this->_impl_.sorting_code_.Set(from._internal_sorting_code(), 
      _this->GetArenaForAllocation());
  }
  _impl_.administrative_area_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.administrative_area_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_administrative_area().empty()) {
    _this->_impl_.administrative_area_.Set(from._internal_administrative_area(), 
      _this->GetArenaForAllocation());
  }
  _impl_.locality_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.locality_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_locality().empty()) {
    _this->_impl_.locality_.Set(from._internal_locality(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sublocality_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sublocality_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sublocality().empty()) {
    _this->_impl_.sublocality_.Set(from._internal_sublocality(), 
      _this->GetArenaForAllocation());
  }
  _impl_.organization_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.organization_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_organization().empty()) {
    _this->_impl_.organization_.Set(from._internal_organization(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.revision_ = from._impl_.revision_;
  // @@protoc_insertion_point(copy_constructor:google.type.PostalAddress)
}

inline void PostalAddress::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.address_lines_){arena}
    , decltype(_impl_.recipients_){arena}
    , decltype(_impl_.region_code_){}
    , decltype(_impl_.language_code_){}
    , decltype(_impl_.postal_code_){}
    , decltype(_impl_.sorting_code_){}
    , decltype(_impl_.administrative_area_){}
    , decltype(_impl_.locality_){}
    , decltype(_impl_.sublocality_){}
    , decltype(_impl_.organization_){}
    , decltype(_impl_.revision_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.region_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.region_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.language_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.language_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.postal_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.postal_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sorting_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sorting_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.administrative_area_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.administrative_area_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.locality_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.locality_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sublocality_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sublocality_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.organization_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.organization_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PostalAddress::~PostalAddress() {
  // @@protoc_insertion_point(destructor:google.type.PostalAddress)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PostalAddress::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.address_lines_.~RepeatedPtrField();
  _impl_.recipients_.~RepeatedPtrField();
  _impl_.region_code_.Destroy();
  _impl_.language_code_.Destroy();
  _impl_.postal_code_.Destroy();
  _impl_.sorting_code_.Destroy();
  _impl_.administrative_area_.Destroy();
  _impl_.locality_.Destroy();
  _impl_.sublocality_.Destroy();
  _impl_.organization_.Destroy();
}

void PostalAddress::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PostalAddress::Clear() {
// @@protoc_insertion_point(message_clear_start:google.type.PostalAddress)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.address_lines_.Clear();
  _impl_.recipients_.Clear();
  _impl_.region_code_.ClearToEmpty();
  _impl_.language_code_.ClearToEmpty();
  _impl_.postal_code_.ClearToEmpty();
  _impl_.sorting_code_.ClearToEmpty();
  _impl_.administrative_area_.ClearToEmpty();
  _impl_.locality_.ClearToEmpty();
  _impl_.sublocality_.ClearToEmpty();
  _impl_.organization_.ClearToEmpty();
  _impl_.revision_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PostalAddress::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 revision = 1 [json_name = "revision"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.revision_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string region_code = 2 [json_name = "regionCode"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_region_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "google.type.PostalAddress.region_code"));
        } else
          goto handle_unusual;
        continue;
      // string language_code = 3 [json_name = "languageCode"];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_language_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "google.type.PostalAddress.language_code"));
        } else
          goto handle_unusual;
        continue;
      // string postal_code = 4 [json_name = "postalCode"];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_postal_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "google.type.PostalAddress.postal_code"));
        } else
          goto handle_unusual;
        continue;
      // string sorting_code = 5 [json_name = "sortingCode"];
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_sorting_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "google.type.PostalAddress.sorting_code"));
        } else
          goto handle_unusual;
        continue;
      // string administrative_area = 6 [json_name = "administrativeArea"];
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_administrative_area();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "google.type.PostalAddress.administrative_area"));
        } else
          goto handle_unusual;
        continue;
      // string locality = 7 [json_name = "locality"];
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_locality();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "google.type.PostalAddress.locality"));
        } else
          goto handle_unusual;
        continue;
      // string sublocality = 8 [json_name = "sublocality"];
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_sublocality();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "google.type.PostalAddress.sublocality"));
        } else
          goto handle_unusual;
        continue;
      // repeated string address_lines = 9 [json_name = "addressLines"];
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_address_lines();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "google.type.PostalAddress.address_lines"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<74>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated string recipients = 10 [json_name = "recipients"];
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_recipients();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "google.type.PostalAddress.recipients"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<82>(ptr));
        } else
          goto handle_unusual;
        continue;
      // string organization = 11 [json_name = "organization"];
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_organization();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "google.type.PostalAddress.organization"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PostalAddress::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.type.PostalAddress)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 revision = 1 [json_name = "revision"];
  if (this->_internal_revision() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_revision(), target);
  }

  // string region_code = 2 [json_name = "regionCode"];
  if (!this->_internal_region_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_region_code().data(), static_cast<int>(this->_internal_region_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.type.PostalAddress.region_code");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_region_code(), target);
  }

  // string language_code = 3 [json_name = "languageCode"];
  if (!this->_internal_language_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_language_code().data(), static_cast<int>(this->_internal_language_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.type.PostalAddress.language_code");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_language_code(), target);
  }

  // string postal_code = 4 [json_name = "postalCode"];
  if (!this->_internal_postal_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_postal_code().data(), static_cast<int>(this->_internal_postal_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.type.PostalAddress.postal_code");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_postal_code(), target);
  }

  // string sorting_code = 5 [json_name = "sortingCode"];
  if (!this->_internal_sorting_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sorting_code().data(), static_cast<int>(this->_internal_sorting_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.type.PostalAddress.sorting_code");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_sorting_code(), target);
  }

  // string administrative_area = 6 [json_name = "administrativeArea"];
  if (!this->_internal_administrative_area().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_administrative_area().data(), static_cast<int>(this->_internal_administrative_area().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.type.PostalAddress.administrative_area");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_administrative_area(), target);
  }

  // string locality = 7 [json_name = "locality"];
  if (!this->_internal_locality().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_locality().data(), static_cast<int>(this->_internal_locality().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.type.PostalAddress.locality");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_locality(), target);
  }

  // string sublocality = 8 [json_name = "sublocality"];
  if (!this->_internal_sublocality().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sublocality().data(), static_cast<int>(this->_internal_sublocality().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.type.PostalAddress.sublocality");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_sublocality(), target);
  }

  // repeated string address_lines = 9 [json_name = "addressLines"];
  for (int i = 0, n = this->_internal_address_lines_size(); i < n; i++) {
    const auto& s = this->_internal_address_lines(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.type.PostalAddress.address_lines");
    target = stream->WriteString(9, s, target);
  }

  // repeated string recipients = 10 [json_name = "recipients"];
  for (int i = 0, n = this->_internal_recipients_size(); i < n; i++) {
    const auto& s = this->_internal_recipients(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.type.PostalAddress.recipients");
    target = stream->WriteString(10, s, target);
  }

  // string organization = 11 [json_name = "organization"];
  if (!this->_internal_organization().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_organization().data(), static_cast<int>(this->_internal_organization().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.type.PostalAddress.organization");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_organization(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.type.PostalAddress)
  return target;
}

size_t PostalAddress::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.type.PostalAddress)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string address_lines = 9 [json_name = "addressLines"];
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.address_lines_.size());
  for (int i = 0, n = _impl_.address_lines_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.address_lines_.Get(i));
  }

  // repeated string recipients = 10 [json_name = "recipients"];
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.recipients_.size());
  for (int i = 0, n = _impl_.recipients_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.recipients_.Get(i));
  }

  // string region_code = 2 [json_name = "regionCode"];
  if (!this->_internal_region_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_region_code());
  }

  // string language_code = 3 [json_name = "languageCode"];
  if (!this->_internal_language_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_language_code());
  }

  // string postal_code = 4 [json_name = "postalCode"];
  if (!this->_internal_postal_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_postal_code());
  }

  // string sorting_code = 5 [json_name = "sortingCode"];
  if (!this->_internal_sorting_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sorting_code());
  }

  // string administrative_area = 6 [json_name = "administrativeArea"];
  if (!this->_internal_administrative_area().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_administrative_area());
  }

  // string locality = 7 [json_name = "locality"];
  if (!this->_internal_locality().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_locality());
  }

  // string sublocality = 8 [json_name = "sublocality"];
  if (!this->_internal_sublocality().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sublocality());
  }

  // string organization = 11 [json_name = "organization"];
  if (!this->_internal_organization().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_organization());
  }

  // int32 revision = 1 [json_name = "revision"];
  if (this->_internal_revision() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_revision());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PostalAddress::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PostalAddress::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PostalAddress::GetClassData() const { return &_class_data_; }


void PostalAddress::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PostalAddress*>(&to_msg);
  auto& from = static_cast<const PostalAddress&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.type.PostalAddress)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.address_lines_.MergeFrom(from._impl_.address_lines_);
  _this->_impl_.recipients_.MergeFrom(from._impl_.recipients_);
  if (!from._internal_region_code().empty()) {
    _this->_internal_set_region_code(from._internal_region_code());
  }
  if (!from._internal_language_code().empty()) {
    _this->_internal_set_language_code(from._internal_language_code());
  }
  if (!from._internal_postal_code().empty()) {
    _this->_internal_set_postal_code(from._internal_postal_code());
  }
  if (!from._internal_sorting_code().empty()) {
    _this->_internal_set_sorting_code(from._internal_sorting_code());
  }
  if (!from._internal_administrative_area().empty()) {
    _this->_internal_set_administrative_area(from._internal_administrative_area());
  }
  if (!from._internal_locality().empty()) {
    _this->_internal_set_locality(from._internal_locality());
  }
  if (!from._internal_sublocality().empty()) {
    _this->_internal_set_sublocality(from._internal_sublocality());
  }
  if (!from._internal_organization().empty()) {
    _this->_internal_set_organization(from._internal_organization());
  }
  if (from._internal_revision() != 0) {
    _this->_internal_set_revision(from._internal_revision());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PostalAddress::CopyFrom(const PostalAddress& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.type.PostalAddress)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PostalAddress::IsInitialized() const {
  return true;
}

void PostalAddress::InternalSwap(PostalAddress* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.address_lines_.InternalSwap(&other->_impl_.address_lines_);
  _impl_.recipients_.InternalSwap(&other->_impl_.recipients_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.region_code_, lhs_arena,
      &other->_impl_.region_code_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.language_code_, lhs_arena,
      &other->_impl_.language_code_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.postal_code_, lhs_arena,
      &other->_impl_.postal_code_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sorting_code_, lhs_arena,
      &other->_impl_.sorting_code_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.administrative_area_, lhs_arena,
      &other->_impl_.administrative_area_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.locality_, lhs_arena,
      &other->_impl_.locality_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sublocality_, lhs_arena,
      &other->_impl_.sublocality_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.organization_, lhs_arena,
      &other->_impl_.organization_, rhs_arena
  );
  swap(_impl_.revision_, other->_impl_.revision_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PostalAddress::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2ftype_2fpostal_5faddress_2eproto_getter, &descriptor_table_google_2ftype_2fpostal_5faddress_2eproto_once,
      file_level_metadata_google_2ftype_2fpostal_5faddress_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace type
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::google::type::PostalAddress*
Arena::CreateMaybeMessage< ::google::type::PostalAddress >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::type::PostalAddress >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
