version: 3

includes:
  docker:
    taskfile: ./docker/Taskfile.yaml

tasks:
  default:
    cmds:
      - task -l

  generate:
    desc: Generate the protobuf and gRPC stubs
    cmds:
      - docker run --rm -v "{{.TASKFILE_DIR}}:/workspace" -w /workspace bufbuild/buf generate
