// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openfga/v1/errors_ignore.proto

#include "openfga/v1/errors_ignore.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace openfga {
namespace v1 {
PROTOBUF_CONSTEXPR ValidationErrorMessageResponse::ValidationErrorMessageResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ValidationErrorMessageResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ValidationErrorMessageResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ValidationErrorMessageResponseDefaultTypeInternal() {}
  union {
    ValidationErrorMessageResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ValidationErrorMessageResponseDefaultTypeInternal _ValidationErrorMessageResponse_default_instance_;
PROTOBUF_CONSTEXPR UnauthenticatedResponse::UnauthenticatedResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UnauthenticatedResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnauthenticatedResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnauthenticatedResponseDefaultTypeInternal() {}
  union {
    UnauthenticatedResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnauthenticatedResponseDefaultTypeInternal _UnauthenticatedResponse_default_instance_;
PROTOBUF_CONSTEXPR UnprocessableContentMessageResponse::UnprocessableContentMessageResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UnprocessableContentMessageResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnprocessableContentMessageResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnprocessableContentMessageResponseDefaultTypeInternal() {}
  union {
    UnprocessableContentMessageResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnprocessableContentMessageResponseDefaultTypeInternal _UnprocessableContentMessageResponse_default_instance_;
PROTOBUF_CONSTEXPR InternalErrorMessageResponse::InternalErrorMessageResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InternalErrorMessageResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InternalErrorMessageResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InternalErrorMessageResponseDefaultTypeInternal() {}
  union {
    InternalErrorMessageResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InternalErrorMessageResponseDefaultTypeInternal _InternalErrorMessageResponse_default_instance_;
PROTOBUF_CONSTEXPR PathUnknownErrorMessageResponse::PathUnknownErrorMessageResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PathUnknownErrorMessageResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PathUnknownErrorMessageResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PathUnknownErrorMessageResponseDefaultTypeInternal() {}
  union {
    PathUnknownErrorMessageResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PathUnknownErrorMessageResponseDefaultTypeInternal _PathUnknownErrorMessageResponse_default_instance_;
PROTOBUF_CONSTEXPR AbortedMessageResponse::AbortedMessageResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AbortedMessageResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AbortedMessageResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AbortedMessageResponseDefaultTypeInternal() {}
  union {
    AbortedMessageResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AbortedMessageResponseDefaultTypeInternal _AbortedMessageResponse_default_instance_;
PROTOBUF_CONSTEXPR ErrorMessageRequest::ErrorMessageRequest(
    ::_pbi::ConstantInitialized) {}
struct ErrorMessageRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ErrorMessageRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ErrorMessageRequestDefaultTypeInternal() {}
  union {
    ErrorMessageRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ErrorMessageRequestDefaultTypeInternal _ErrorMessageRequest_default_instance_;
PROTOBUF_CONSTEXPR ForbiddenResponse::ForbiddenResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ForbiddenResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ForbiddenResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ForbiddenResponseDefaultTypeInternal() {}
  union {
    ForbiddenResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ForbiddenResponseDefaultTypeInternal _ForbiddenResponse_default_instance_;
}  // namespace v1
}  // namespace openfga
static ::_pb::Metadata file_level_metadata_openfga_2fv1_2ferrors_5fignore_2eproto[8];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_openfga_2fv1_2ferrors_5fignore_2eproto[5];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_openfga_2fv1_2ferrors_5fignore_2eproto = nullptr;

const uint32_t TableStruct_openfga_2fv1_2ferrors_5fignore_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::ValidationErrorMessageResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::ValidationErrorMessageResponse, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::openfga::v1::ValidationErrorMessageResponse, _impl_.message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::UnauthenticatedResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::UnauthenticatedResponse, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::openfga::v1::UnauthenticatedResponse, _impl_.message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::UnprocessableContentMessageResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::UnprocessableContentMessageResponse, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::openfga::v1::UnprocessableContentMessageResponse, _impl_.message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::InternalErrorMessageResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::InternalErrorMessageResponse, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::openfga::v1::InternalErrorMessageResponse, _impl_.message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::PathUnknownErrorMessageResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::PathUnknownErrorMessageResponse, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::openfga::v1::PathUnknownErrorMessageResponse, _impl_.message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::AbortedMessageResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::AbortedMessageResponse, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::openfga::v1::AbortedMessageResponse, _impl_.message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::ErrorMessageRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::ForbiddenResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::openfga::v1::ForbiddenResponse, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::openfga::v1::ForbiddenResponse, _impl_.message_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::openfga::v1::ValidationErrorMessageResponse)},
  { 8, -1, -1, sizeof(::openfga::v1::UnauthenticatedResponse)},
  { 16, -1, -1, sizeof(::openfga::v1::UnprocessableContentMessageResponse)},
  { 24, -1, -1, sizeof(::openfga::v1::InternalErrorMessageResponse)},
  { 32, -1, -1, sizeof(::openfga::v1::PathUnknownErrorMessageResponse)},
  { 40, -1, -1, sizeof(::openfga::v1::AbortedMessageResponse)},
  { 48, -1, -1, sizeof(::openfga::v1::ErrorMessageRequest)},
  { 54, -1, -1, sizeof(::openfga::v1::ForbiddenResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::openfga::v1::_ValidationErrorMessageResponse_default_instance_._instance,
  &::openfga::v1::_UnauthenticatedResponse_default_instance_._instance,
  &::openfga::v1::_UnprocessableContentMessageResponse_default_instance_._instance,
  &::openfga::v1::_InternalErrorMessageResponse_default_instance_._instance,
  &::openfga::v1::_PathUnknownErrorMessageResponse_default_instance_._instance,
  &::openfga::v1::_AbortedMessageResponse_default_instance_._instance,
  &::openfga::v1::_ErrorMessageRequest_default_instance_._instance,
  &::openfga::v1::_ForbiddenResponse_default_instance_._instance,
};

const char descriptor_table_protodef_openfga_2fv1_2ferrors_5fignore_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036openfga/v1/errors_ignore.proto\022\nopenfg"
  "a.v1\032.protoc-gen-openapiv2/options/annot"
  "ations.proto\"\255\001\n\036ValidationErrorMessageR"
  "esponse\022)\n\004code\030\001 \001(\0162\025.openfga.v1.Error"
  "CodeR\004code\022\030\n\007message\030\002 \001(\tR\007message:F\222A"
  "C2A{\"code\":\"validation_error\", \"message\""
  ":\"Generic validation error\"}\"\234\001\n\027Unauthe"
  "nticatedResponse\022)\n\004code\030\001 \001(\0162\025.openfga"
  ".v1.ErrorCodeR\004code\022\030\n\007message\030\002 \001(\tR\007me"
  "ssage:<\222A927{\"code\":\"unauthenticated\", \""
  "message\":\"unauthenticated\"}\"\341\001\n#Unproces"
  "sableContentMessageResponse\022=\n\004code\030\001 \001("
  "\0162).openfga.v1.UnprocessableContentError"
  "CodeR\004code\022\030\n\007message\030\002 \001(\tR\007message:a\222A"
  "^2\\{\"code\":\"throttled_timeout_error\", \"m"
  "essage\":\"timeout due to throttling on co"
  "mplex request\"}\"\256\001\n\034InternalErrorMessage"
  "Response\0221\n\004code\030\001 \001(\0162\035.openfga.v1.Inte"
  "rnalErrorCodeR\004code\022\030\n\007message\030\002 \001(\tR\007me"
  "ssage:A\222A>2<{\"code\":\"internal_error\", \"m"
  "essage\":\"Internal Server Error\"}\"\264\001\n\037Pat"
  "hUnknownErrorMessageResponse\0221\n\004code\030\001 \001"
  "(\0162\035.openfga.v1.NotFoundErrorCodeR\004code\022"
  "\030\n\007message\030\002 \001(\tR\007message:D\222AA2\?{\"code\":"
  "\"undefined_endpoint\", \"message\":\"Endpoin"
  "t not enabled\"}\"|\n\026AbortedMessageRespons"
  "e\022\022\n\004code\030\001 \001(\tR\004code\022\030\n\007message\030\002 \001(\tR\007"
  "message:4\222A12/{\"code\":\"10\", \"message\":\"t"
  "ransaction conflict\"}\"\025\n\023ErrorMessageReq"
  "uest\"\272\001\n\021ForbiddenResponse\022-\n\004code\030\001 \001(\016"
  "2\031.openfga.v1.AuthErrorCodeR\004code\022\030\n\007mes"
  "sage\030\002 \001(\tR\007message:\\\222AY2W{\"code\":\"forbi"
  "dden\", \"message\":\"the principal is not a"
  "uthorized to perform the action\"}*\205\002\n\rAu"
  "thErrorCode\022\021\n\rno_auth_error\020\000\022 \n\033auth_f"
  "ailed_invalid_subject\020\351\007\022!\n\034auth_failed_"
  "invalid_audience\020\352\007\022\037\n\032auth_failed_inval"
  "id_issuer\020\353\007\022\023\n\016invalid_claims\020\354\007\022%\n aut"
  "h_failed_invalid_bearer_token\020\355\007\022\031\n\024bear"
  "er_token_missing\020\362\007\022\024\n\017unauthenticated\020\334"
  "\013\022\016\n\tforbidden\020\300\014*\243\014\n\tErrorCode\022\014\n\010no_er"
  "ror\020\000\022\025\n\020validation_error\020\320\017\022\"\n\035authoriz"
  "ation_model_not_found\020\321\017\022/\n*authorizatio"
  "n_model_resolution_too_complex\020\322\017\022\030\n\023inv"
  "alid_write_input\020\323\017\0221\n,cannot_allow_dupl"
  "icate_tuples_in_one_request\020\324\017\0220\n+cannot"
  "_allow_duplicate_types_in_one_request\020\325\017"
  "\0225\n0cannot_allow_multiple_references_to_"
  "one_relation\020\326\017\022\037\n\032invalid_continuation_"
  "token\020\327\017\022\026\n\021invalid_tuple_set\020\330\017\022\030\n\023inva"
  "lid_check_input\020\331\017\022\031\n\024invalid_expand_inp"
  "ut\020\332\017\022\031\n\024unsupported_user_set\020\333\017\022\032\n\025inva"
  "lid_object_format\020\334\017\022&\n!write_failed_due"
  "_to_invalid_input\020\341\017\022-\n(authorization_mo"
  "del_assertions_not_found\020\342\017\022)\n$latest_au"
  "thorization_model_not_found\020\344\017\022\023\n\016type_n"
  "ot_found\020\345\017\022\027\n\022relation_not_found\020\346\017\022\036\n\031"
  "empty_relation_definition\020\347\017\022\021\n\014invalid_"
  "user\020\351\017\022\022\n\rinvalid_tuple\020\353\017\022\025\n\020unknown_r"
  "elation\020\354\017\022\034\n\027store_id_invalid_length\020\356\017"
  "\022\036\n\031assertions_too_many_items\020\361\017\022\020\n\013id_t"
  "oo_long\020\362\017\022$\n\037authorization_model_id_too"
  "_long\020\364\017\022\"\n\035tuple_key_value_not_specifie"
  "d\020\365\017\022)\n$tuple_keys_too_many_or_too_few_i"
  "tems\020\366\017\022\026\n\021page_size_invalid\020\367\017\022\030\n\023param"
  "_missing_value\020\370\017\022\"\n\035difference_base_mis"
  "sing_value\020\371\017\022 \n\033subtract_base_missing_v"
  "alue\020\372\017\022\024\n\017object_too_long\020\373\017\022\026\n\021relatio"
  "n_too_long\020\374\017\022#\n\036type_definitions_too_fe"
  "w_items\020\375\017\022\030\n\023type_invalid_length\020\376\017\022\031\n\024"
  "type_invalid_pattern\020\377\017\022\034\n\027relations_too"
  "_few_items\020\200\020\022\027\n\022relations_too_long\020\201\020\022\036"
  "\n\031relations_invalid_pattern\020\202\020\022\033\n\026object"
  "_invalid_pattern\020\203\020\0222\n-query_string_type"
  "_continuation_token_mismatch\020\204\020\022\032\n\025excee"
  "ded_entity_limit\020\205\020\022\035\n\030invalid_contextua"
  "l_tuple\020\206\020\022\037\n\032duplicate_contextual_tuple"
  "\020\207\020\022 \n\033invalid_authorization_model\020\210\020\022\037\n"
  "\032unsupported_schema_version\020\211\020\022\016\n\tcancel"
  "led\020\212\020\022\027\n\022invalid_start_time\020\213\020*Z\n\035Unpro"
  "cessableContentErrorCode\022\033\n\027no_throttled"
  "_error_code\020\000\022\034\n\027throttled_timeout_error"
  "\020\254\033*\342\001\n\021InternalErrorCode\022\025\n\021no_internal"
  "_error\020\000\022\023\n\016internal_error\020\240\037\022\026\n\021deadlin"
  "e_exceeded\020\244\037\022\023\n\016already_exists\020\245\037\022\027\n\022re"
  "source_exhausted\020\246\037\022\030\n\023failed_preconditi"
  "on\020\247\037\022\014\n\007aborted\020\250\037\022\021\n\014out_of_range\020\251\037\022\020"
  "\n\013unavailable\020\252\037\022\016\n\tdata_loss\020\253\037*q\n\021NotF"
  "oundErrorCode\022\026\n\022no_not_found_error\020\000\022\027\n"
  "\022undefined_endpoint\020\210\'\022\027\n\022store_id_not_f"
  "ound\020\212\'\022\022\n\runimplemented\020\214\'Bl\n\016com.openf"
  "ga.v1B\021ErrorsIgnoreProtoP\001\242\002\003OXX\252\002\nOpenf"
  "ga.V1\312\002\nOpenfga\\V1\342\002\026Openfga\\V1\\GPBMetad"
  "ata\352\002\013Openfga::V1b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_deps[1] = {
  &::descriptor_table_protoc_2dgen_2dopenapiv2_2foptions_2fannotations_2eproto,
};
static ::_pbi::once_flag descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto = {
    false, false, 3745, descriptor_table_protodef_openfga_2fv1_2ferrors_5fignore_2eproto,
    "openfga/v1/errors_ignore.proto",
    &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_once, descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_deps, 1, 8,
    schemas, file_default_instances, TableStruct_openfga_2fv1_2ferrors_5fignore_2eproto::offsets,
    file_level_metadata_openfga_2fv1_2ferrors_5fignore_2eproto, file_level_enum_descriptors_openfga_2fv1_2ferrors_5fignore_2eproto,
    file_level_service_descriptors_openfga_2fv1_2ferrors_5fignore_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_getter() {
  return &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_openfga_2fv1_2ferrors_5fignore_2eproto(&descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto);
namespace openfga {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AuthErrorCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto);
  return file_level_enum_descriptors_openfga_2fv1_2ferrors_5fignore_2eproto[0];
}
bool AuthErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 1010:
    case 1500:
    case 1600:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto);
  return file_level_enum_descriptors_openfga_2fv1_2ferrors_5fignore_2eproto[1];
}
bool ErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 2000:
    case 2001:
    case 2002:
    case 2003:
    case 2004:
    case 2005:
    case 2006:
    case 2007:
    case 2008:
    case 2009:
    case 2010:
    case 2011:
    case 2012:
    case 2017:
    case 2018:
    case 2020:
    case 2021:
    case 2022:
    case 2023:
    case 2025:
    case 2027:
    case 2028:
    case 2030:
    case 2033:
    case 2034:
    case 2036:
    case 2037:
    case 2038:
    case 2039:
    case 2040:
    case 2041:
    case 2042:
    case 2043:
    case 2044:
    case 2045:
    case 2046:
    case 2047:
    case 2048:
    case 2049:
    case 2050:
    case 2051:
    case 2052:
    case 2053:
    case 2054:
    case 2055:
    case 2056:
    case 2057:
    case 2058:
    case 2059:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* UnprocessableContentErrorCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto);
  return file_level_enum_descriptors_openfga_2fv1_2ferrors_5fignore_2eproto[2];
}
bool UnprocessableContentErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 3500:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* InternalErrorCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto);
  return file_level_enum_descriptors_openfga_2fv1_2ferrors_5fignore_2eproto[3];
}
bool InternalErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 4000:
    case 4004:
    case 4005:
    case 4006:
    case 4007:
    case 4008:
    case 4009:
    case 4010:
    case 4011:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* NotFoundErrorCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto);
  return file_level_enum_descriptors_openfga_2fv1_2ferrors_5fignore_2eproto[4];
}
bool NotFoundErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 5000:
    case 5002:
    case 5004:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class ValidationErrorMessageResponse::_Internal {
 public:
};

ValidationErrorMessageResponse::ValidationErrorMessageResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:openfga.v1.ValidationErrorMessageResponse)
}
ValidationErrorMessageResponse::ValidationErrorMessageResponse(const ValidationErrorMessageResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ValidationErrorMessageResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.code_ = from._impl_.code_;
  // @@protoc_insertion_point(copy_constructor:openfga.v1.ValidationErrorMessageResponse)
}

inline void ValidationErrorMessageResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ValidationErrorMessageResponse::~ValidationErrorMessageResponse() {
  // @@protoc_insertion_point(destructor:openfga.v1.ValidationErrorMessageResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ValidationErrorMessageResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void ValidationErrorMessageResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ValidationErrorMessageResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:openfga.v1.ValidationErrorMessageResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ValidationErrorMessageResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .openfga.v1.ErrorCode code = 1 [json_name = "code"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_code(static_cast<::openfga::v1::ErrorCode>(val));
        } else
          goto handle_unusual;
        continue;
      // string message = 2 [json_name = "message"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "openfga.v1.ValidationErrorMessageResponse.message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ValidationErrorMessageResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfga.v1.ValidationErrorMessageResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .openfga.v1.ErrorCode code = 1 [json_name = "code"];
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_code(), target);
  }

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openfga.v1.ValidationErrorMessageResponse.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfga.v1.ValidationErrorMessageResponse)
  return target;
}

size_t ValidationErrorMessageResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfga.v1.ValidationErrorMessageResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // .openfga.v1.ErrorCode code = 1 [json_name = "code"];
  if (this->_internal_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ValidationErrorMessageResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ValidationErrorMessageResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ValidationErrorMessageResponse::GetClassData() const { return &_class_data_; }


void ValidationErrorMessageResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ValidationErrorMessageResponse*>(&to_msg);
  auto& from = static_cast<const ValidationErrorMessageResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:openfga.v1.ValidationErrorMessageResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ValidationErrorMessageResponse::CopyFrom(const ValidationErrorMessageResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfga.v1.ValidationErrorMessageResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ValidationErrorMessageResponse::IsInitialized() const {
  return true;
}

void ValidationErrorMessageResponse::InternalSwap(ValidationErrorMessageResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  swap(_impl_.code_, other->_impl_.code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ValidationErrorMessageResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_getter, &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_once,
      file_level_metadata_openfga_2fv1_2ferrors_5fignore_2eproto[0]);
}

// ===================================================================

class UnauthenticatedResponse::_Internal {
 public:
};

UnauthenticatedResponse::UnauthenticatedResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:openfga.v1.UnauthenticatedResponse)
}
UnauthenticatedResponse::UnauthenticatedResponse(const UnauthenticatedResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UnauthenticatedResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.code_ = from._impl_.code_;
  // @@protoc_insertion_point(copy_constructor:openfga.v1.UnauthenticatedResponse)
}

inline void UnauthenticatedResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UnauthenticatedResponse::~UnauthenticatedResponse() {
  // @@protoc_insertion_point(destructor:openfga.v1.UnauthenticatedResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UnauthenticatedResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void UnauthenticatedResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UnauthenticatedResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:openfga.v1.UnauthenticatedResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UnauthenticatedResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .openfga.v1.ErrorCode code = 1 [json_name = "code"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_code(static_cast<::openfga::v1::ErrorCode>(val));
        } else
          goto handle_unusual;
        continue;
      // string message = 2 [json_name = "message"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "openfga.v1.UnauthenticatedResponse.message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UnauthenticatedResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfga.v1.UnauthenticatedResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .openfga.v1.ErrorCode code = 1 [json_name = "code"];
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_code(), target);
  }

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openfga.v1.UnauthenticatedResponse.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfga.v1.UnauthenticatedResponse)
  return target;
}

size_t UnauthenticatedResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfga.v1.UnauthenticatedResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // .openfga.v1.ErrorCode code = 1 [json_name = "code"];
  if (this->_internal_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UnauthenticatedResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UnauthenticatedResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UnauthenticatedResponse::GetClassData() const { return &_class_data_; }


void UnauthenticatedResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UnauthenticatedResponse*>(&to_msg);
  auto& from = static_cast<const UnauthenticatedResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:openfga.v1.UnauthenticatedResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UnauthenticatedResponse::CopyFrom(const UnauthenticatedResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfga.v1.UnauthenticatedResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnauthenticatedResponse::IsInitialized() const {
  return true;
}

void UnauthenticatedResponse::InternalSwap(UnauthenticatedResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  swap(_impl_.code_, other->_impl_.code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata UnauthenticatedResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_getter, &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_once,
      file_level_metadata_openfga_2fv1_2ferrors_5fignore_2eproto[1]);
}

// ===================================================================

class UnprocessableContentMessageResponse::_Internal {
 public:
};

UnprocessableContentMessageResponse::UnprocessableContentMessageResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:openfga.v1.UnprocessableContentMessageResponse)
}
UnprocessableContentMessageResponse::UnprocessableContentMessageResponse(const UnprocessableContentMessageResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UnprocessableContentMessageResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.code_ = from._impl_.code_;
  // @@protoc_insertion_point(copy_constructor:openfga.v1.UnprocessableContentMessageResponse)
}

inline void UnprocessableContentMessageResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UnprocessableContentMessageResponse::~UnprocessableContentMessageResponse() {
  // @@protoc_insertion_point(destructor:openfga.v1.UnprocessableContentMessageResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UnprocessableContentMessageResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void UnprocessableContentMessageResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UnprocessableContentMessageResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:openfga.v1.UnprocessableContentMessageResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UnprocessableContentMessageResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .openfga.v1.UnprocessableContentErrorCode code = 1 [json_name = "code"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_code(static_cast<::openfga::v1::UnprocessableContentErrorCode>(val));
        } else
          goto handle_unusual;
        continue;
      // string message = 2 [json_name = "message"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "openfga.v1.UnprocessableContentMessageResponse.message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UnprocessableContentMessageResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfga.v1.UnprocessableContentMessageResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .openfga.v1.UnprocessableContentErrorCode code = 1 [json_name = "code"];
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_code(), target);
  }

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openfga.v1.UnprocessableContentMessageResponse.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfga.v1.UnprocessableContentMessageResponse)
  return target;
}

size_t UnprocessableContentMessageResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfga.v1.UnprocessableContentMessageResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // .openfga.v1.UnprocessableContentErrorCode code = 1 [json_name = "code"];
  if (this->_internal_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UnprocessableContentMessageResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UnprocessableContentMessageResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UnprocessableContentMessageResponse::GetClassData() const { return &_class_data_; }


void UnprocessableContentMessageResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UnprocessableContentMessageResponse*>(&to_msg);
  auto& from = static_cast<const UnprocessableContentMessageResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:openfga.v1.UnprocessableContentMessageResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UnprocessableContentMessageResponse::CopyFrom(const UnprocessableContentMessageResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfga.v1.UnprocessableContentMessageResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnprocessableContentMessageResponse::IsInitialized() const {
  return true;
}

void UnprocessableContentMessageResponse::InternalSwap(UnprocessableContentMessageResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  swap(_impl_.code_, other->_impl_.code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata UnprocessableContentMessageResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_getter, &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_once,
      file_level_metadata_openfga_2fv1_2ferrors_5fignore_2eproto[2]);
}

// ===================================================================

class InternalErrorMessageResponse::_Internal {
 public:
};

InternalErrorMessageResponse::InternalErrorMessageResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:openfga.v1.InternalErrorMessageResponse)
}
InternalErrorMessageResponse::InternalErrorMessageResponse(const InternalErrorMessageResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InternalErrorMessageResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.code_ = from._impl_.code_;
  // @@protoc_insertion_point(copy_constructor:openfga.v1.InternalErrorMessageResponse)
}

inline void InternalErrorMessageResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

InternalErrorMessageResponse::~InternalErrorMessageResponse() {
  // @@protoc_insertion_point(destructor:openfga.v1.InternalErrorMessageResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InternalErrorMessageResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void InternalErrorMessageResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InternalErrorMessageResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:openfga.v1.InternalErrorMessageResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InternalErrorMessageResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .openfga.v1.InternalErrorCode code = 1 [json_name = "code"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_code(static_cast<::openfga::v1::InternalErrorCode>(val));
        } else
          goto handle_unusual;
        continue;
      // string message = 2 [json_name = "message"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "openfga.v1.InternalErrorMessageResponse.message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InternalErrorMessageResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfga.v1.InternalErrorMessageResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .openfga.v1.InternalErrorCode code = 1 [json_name = "code"];
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_code(), target);
  }

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openfga.v1.InternalErrorMessageResponse.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfga.v1.InternalErrorMessageResponse)
  return target;
}

size_t InternalErrorMessageResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfga.v1.InternalErrorMessageResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // .openfga.v1.InternalErrorCode code = 1 [json_name = "code"];
  if (this->_internal_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InternalErrorMessageResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InternalErrorMessageResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InternalErrorMessageResponse::GetClassData() const { return &_class_data_; }


void InternalErrorMessageResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InternalErrorMessageResponse*>(&to_msg);
  auto& from = static_cast<const InternalErrorMessageResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:openfga.v1.InternalErrorMessageResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InternalErrorMessageResponse::CopyFrom(const InternalErrorMessageResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfga.v1.InternalErrorMessageResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InternalErrorMessageResponse::IsInitialized() const {
  return true;
}

void InternalErrorMessageResponse::InternalSwap(InternalErrorMessageResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  swap(_impl_.code_, other->_impl_.code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InternalErrorMessageResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_getter, &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_once,
      file_level_metadata_openfga_2fv1_2ferrors_5fignore_2eproto[3]);
}

// ===================================================================

class PathUnknownErrorMessageResponse::_Internal {
 public:
};

PathUnknownErrorMessageResponse::PathUnknownErrorMessageResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:openfga.v1.PathUnknownErrorMessageResponse)
}
PathUnknownErrorMessageResponse::PathUnknownErrorMessageResponse(const PathUnknownErrorMessageResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PathUnknownErrorMessageResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.code_ = from._impl_.code_;
  // @@protoc_insertion_point(copy_constructor:openfga.v1.PathUnknownErrorMessageResponse)
}

inline void PathUnknownErrorMessageResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PathUnknownErrorMessageResponse::~PathUnknownErrorMessageResponse() {
  // @@protoc_insertion_point(destructor:openfga.v1.PathUnknownErrorMessageResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PathUnknownErrorMessageResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void PathUnknownErrorMessageResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PathUnknownErrorMessageResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:openfga.v1.PathUnknownErrorMessageResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PathUnknownErrorMessageResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .openfga.v1.NotFoundErrorCode code = 1 [json_name = "code"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_code(static_cast<::openfga::v1::NotFoundErrorCode>(val));
        } else
          goto handle_unusual;
        continue;
      // string message = 2 [json_name = "message"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "openfga.v1.PathUnknownErrorMessageResponse.message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PathUnknownErrorMessageResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfga.v1.PathUnknownErrorMessageResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .openfga.v1.NotFoundErrorCode code = 1 [json_name = "code"];
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_code(), target);
  }

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openfga.v1.PathUnknownErrorMessageResponse.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfga.v1.PathUnknownErrorMessageResponse)
  return target;
}

size_t PathUnknownErrorMessageResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfga.v1.PathUnknownErrorMessageResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // .openfga.v1.NotFoundErrorCode code = 1 [json_name = "code"];
  if (this->_internal_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PathUnknownErrorMessageResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PathUnknownErrorMessageResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PathUnknownErrorMessageResponse::GetClassData() const { return &_class_data_; }


void PathUnknownErrorMessageResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PathUnknownErrorMessageResponse*>(&to_msg);
  auto& from = static_cast<const PathUnknownErrorMessageResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:openfga.v1.PathUnknownErrorMessageResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PathUnknownErrorMessageResponse::CopyFrom(const PathUnknownErrorMessageResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfga.v1.PathUnknownErrorMessageResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PathUnknownErrorMessageResponse::IsInitialized() const {
  return true;
}

void PathUnknownErrorMessageResponse::InternalSwap(PathUnknownErrorMessageResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  swap(_impl_.code_, other->_impl_.code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PathUnknownErrorMessageResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_getter, &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_once,
      file_level_metadata_openfga_2fv1_2ferrors_5fignore_2eproto[4]);
}

// ===================================================================

class AbortedMessageResponse::_Internal {
 public:
};

AbortedMessageResponse::AbortedMessageResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:openfga.v1.AbortedMessageResponse)
}
AbortedMessageResponse::AbortedMessageResponse(const AbortedMessageResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AbortedMessageResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.code_){}
    , decltype(_impl_.message_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_code().empty()) {
    _this->_impl_.code_.Set(from._internal_code(), 
      _this->GetArenaForAllocation());
  }
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:openfga.v1.AbortedMessageResponse)
}

inline void AbortedMessageResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.code_){}
    , decltype(_impl_.message_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AbortedMessageResponse::~AbortedMessageResponse() {
  // @@protoc_insertion_point(destructor:openfga.v1.AbortedMessageResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AbortedMessageResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.code_.Destroy();
  _impl_.message_.Destroy();
}

void AbortedMessageResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AbortedMessageResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:openfga.v1.AbortedMessageResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.code_.ClearToEmpty();
  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AbortedMessageResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string code = 1 [json_name = "code"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "openfga.v1.AbortedMessageResponse.code"));
        } else
          goto handle_unusual;
        continue;
      // string message = 2 [json_name = "message"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "openfga.v1.AbortedMessageResponse.message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AbortedMessageResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfga.v1.AbortedMessageResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string code = 1 [json_name = "code"];
  if (!this->_internal_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_code().data(), static_cast<int>(this->_internal_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openfga.v1.AbortedMessageResponse.code");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_code(), target);
  }

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openfga.v1.AbortedMessageResponse.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfga.v1.AbortedMessageResponse)
  return target;
}

size_t AbortedMessageResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfga.v1.AbortedMessageResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string code = 1 [json_name = "code"];
  if (!this->_internal_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_code());
  }

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AbortedMessageResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AbortedMessageResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AbortedMessageResponse::GetClassData() const { return &_class_data_; }


void AbortedMessageResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AbortedMessageResponse*>(&to_msg);
  auto& from = static_cast<const AbortedMessageResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:openfga.v1.AbortedMessageResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_code().empty()) {
    _this->_internal_set_code(from._internal_code());
  }
  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AbortedMessageResponse::CopyFrom(const AbortedMessageResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfga.v1.AbortedMessageResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AbortedMessageResponse::IsInitialized() const {
  return true;
}

void AbortedMessageResponse::InternalSwap(AbortedMessageResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.code_, lhs_arena,
      &other->_impl_.code_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata AbortedMessageResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_getter, &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_once,
      file_level_metadata_openfga_2fv1_2ferrors_5fignore_2eproto[5]);
}

// ===================================================================

class ErrorMessageRequest::_Internal {
 public:
};

ErrorMessageRequest::ErrorMessageRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:openfga.v1.ErrorMessageRequest)
}
ErrorMessageRequest::ErrorMessageRequest(const ErrorMessageRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  ErrorMessageRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:openfga.v1.ErrorMessageRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ErrorMessageRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ErrorMessageRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ErrorMessageRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_getter, &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_once,
      file_level_metadata_openfga_2fv1_2ferrors_5fignore_2eproto[6]);
}

// ===================================================================

class ForbiddenResponse::_Internal {
 public:
};

ForbiddenResponse::ForbiddenResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:openfga.v1.ForbiddenResponse)
}
ForbiddenResponse::ForbiddenResponse(const ForbiddenResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ForbiddenResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.code_ = from._impl_.code_;
  // @@protoc_insertion_point(copy_constructor:openfga.v1.ForbiddenResponse)
}

inline void ForbiddenResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ForbiddenResponse::~ForbiddenResponse() {
  // @@protoc_insertion_point(destructor:openfga.v1.ForbiddenResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ForbiddenResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void ForbiddenResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ForbiddenResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:openfga.v1.ForbiddenResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ForbiddenResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .openfga.v1.AuthErrorCode code = 1 [json_name = "code"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_code(static_cast<::openfga::v1::AuthErrorCode>(val));
        } else
          goto handle_unusual;
        continue;
      // string message = 2 [json_name = "message"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "openfga.v1.ForbiddenResponse.message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ForbiddenResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfga.v1.ForbiddenResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .openfga.v1.AuthErrorCode code = 1 [json_name = "code"];
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_code(), target);
  }

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openfga.v1.ForbiddenResponse.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfga.v1.ForbiddenResponse)
  return target;
}

size_t ForbiddenResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfga.v1.ForbiddenResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2 [json_name = "message"];
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // .openfga.v1.AuthErrorCode code = 1 [json_name = "code"];
  if (this->_internal_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ForbiddenResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ForbiddenResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ForbiddenResponse::GetClassData() const { return &_class_data_; }


void ForbiddenResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ForbiddenResponse*>(&to_msg);
  auto& from = static_cast<const ForbiddenResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:openfga.v1.ForbiddenResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ForbiddenResponse::CopyFrom(const ForbiddenResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfga.v1.ForbiddenResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ForbiddenResponse::IsInitialized() const {
  return true;
}

void ForbiddenResponse::InternalSwap(ForbiddenResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  swap(_impl_.code_, other->_impl_.code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ForbiddenResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_getter, &descriptor_table_openfga_2fv1_2ferrors_5fignore_2eproto_once,
      file_level_metadata_openfga_2fv1_2ferrors_5fignore_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace openfga
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::openfga::v1::ValidationErrorMessageResponse*
Arena::CreateMaybeMessage< ::openfga::v1::ValidationErrorMessageResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfga::v1::ValidationErrorMessageResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::openfga::v1::UnauthenticatedResponse*
Arena::CreateMaybeMessage< ::openfga::v1::UnauthenticatedResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfga::v1::UnauthenticatedResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::openfga::v1::UnprocessableContentMessageResponse*
Arena::CreateMaybeMessage< ::openfga::v1::UnprocessableContentMessageResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfga::v1::UnprocessableContentMessageResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::openfga::v1::InternalErrorMessageResponse*
Arena::CreateMaybeMessage< ::openfga::v1::InternalErrorMessageResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfga::v1::InternalErrorMessageResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::openfga::v1::PathUnknownErrorMessageResponse*
Arena::CreateMaybeMessage< ::openfga::v1::PathUnknownErrorMessageResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfga::v1::PathUnknownErrorMessageResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::openfga::v1::AbortedMessageResponse*
Arena::CreateMaybeMessage< ::openfga::v1::AbortedMessageResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfga::v1::AbortedMessageResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::openfga::v1::ErrorMessageRequest*
Arena::CreateMaybeMessage< ::openfga::v1::ErrorMessageRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfga::v1::ErrorMessageRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::openfga::v1::ForbiddenResponse*
Arena::CreateMaybeMessage< ::openfga::v1::ForbiddenResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfga::v1::ForbiddenResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
