// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: openfga/v1/openfga_service.proto

#include "openfga/v1/openfga_service.pb.h"
#include "openfga/v1/openfga_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace openfga {
namespace v1 {

static const char* OpenFGAService_method_names[] = {
  "/openfga.v1.OpenFGAService/Read",
  "/openfga.v1.OpenFGAService/Write",
  "/openfga.v1.OpenFGAService/Check",
  "/openfga.v1.OpenFGAService/BatchCheck",
  "/openfga.v1.OpenFGAService/Expand",
  "/openfga.v1.OpenFGAService/ReadAuthorizationModels",
  "/openfga.v1.OpenFGAService/ReadAuthorizationModel",
  "/openfga.v1.OpenFGAService/WriteAuthorizationModel",
  "/openfga.v1.OpenFGAService/WriteAssertions",
  "/openfga.v1.OpenFGAService/ReadAssertions",
  "/openfga.v1.OpenFGAService/ReadChanges",
  "/openfga.v1.OpenFGAService/CreateStore",
  "/openfga.v1.OpenFGAService/UpdateStore",
  "/openfga.v1.OpenFGAService/DeleteStore",
  "/openfga.v1.OpenFGAService/GetStore",
  "/openfga.v1.OpenFGAService/ListStores",
  "/openfga.v1.OpenFGAService/StreamedListObjects",
  "/openfga.v1.OpenFGAService/ListObjects",
  "/openfga.v1.OpenFGAService/ListUsers",
};

std::unique_ptr< OpenFGAService::Stub> OpenFGAService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OpenFGAService::Stub> stub(new OpenFGAService::Stub(channel, options));
  return stub;
}

OpenFGAService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Read_(OpenFGAService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Write_(OpenFGAService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Check_(OpenFGAService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchCheck_(OpenFGAService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Expand_(OpenFGAService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadAuthorizationModels_(OpenFGAService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadAuthorizationModel_(OpenFGAService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WriteAuthorizationModel_(OpenFGAService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WriteAssertions_(OpenFGAService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadAssertions_(OpenFGAService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadChanges_(OpenFGAService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateStore_(OpenFGAService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateStore_(OpenFGAService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteStore_(OpenFGAService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStore_(OpenFGAService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListStores_(OpenFGAService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamedListObjects_(OpenFGAService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ListObjects_(OpenFGAService_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListUsers_(OpenFGAService_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status OpenFGAService::Stub::Read(::grpc::ClientContext* context, const ::openfga::v1::ReadRequest& request, ::openfga::v1::ReadResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::ReadRequest, ::openfga::v1::ReadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Read_, context, request, response);
}

void OpenFGAService::Stub::async::Read(::grpc::ClientContext* context, const ::openfga::v1::ReadRequest* request, ::openfga::v1::ReadResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::ReadRequest, ::openfga::v1::ReadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Read_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::Read(::grpc::ClientContext* context, const ::openfga::v1::ReadRequest* request, ::openfga::v1::ReadResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Read_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ReadResponse>* OpenFGAService::Stub::PrepareAsyncReadRaw(::grpc::ClientContext* context, const ::openfga::v1::ReadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::ReadResponse, ::openfga::v1::ReadRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Read_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ReadResponse>* OpenFGAService::Stub::AsyncReadRaw(::grpc::ClientContext* context, const ::openfga::v1::ReadRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::Write(::grpc::ClientContext* context, const ::openfga::v1::WriteRequest& request, ::openfga::v1::WriteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::WriteRequest, ::openfga::v1::WriteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Write_, context, request, response);
}

void OpenFGAService::Stub::async::Write(::grpc::ClientContext* context, const ::openfga::v1::WriteRequest* request, ::openfga::v1::WriteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::WriteRequest, ::openfga::v1::WriteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Write_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::Write(::grpc::ClientContext* context, const ::openfga::v1::WriteRequest* request, ::openfga::v1::WriteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Write_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::WriteResponse>* OpenFGAService::Stub::PrepareAsyncWriteRaw(::grpc::ClientContext* context, const ::openfga::v1::WriteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::WriteResponse, ::openfga::v1::WriteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Write_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::WriteResponse>* OpenFGAService::Stub::AsyncWriteRaw(::grpc::ClientContext* context, const ::openfga::v1::WriteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWriteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::Check(::grpc::ClientContext* context, const ::openfga::v1::CheckRequest& request, ::openfga::v1::CheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::CheckRequest, ::openfga::v1::CheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Check_, context, request, response);
}

void OpenFGAService::Stub::async::Check(::grpc::ClientContext* context, const ::openfga::v1::CheckRequest* request, ::openfga::v1::CheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::CheckRequest, ::openfga::v1::CheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Check_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::Check(::grpc::ClientContext* context, const ::openfga::v1::CheckRequest* request, ::openfga::v1::CheckResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Check_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::CheckResponse>* OpenFGAService::Stub::PrepareAsyncCheckRaw(::grpc::ClientContext* context, const ::openfga::v1::CheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::CheckResponse, ::openfga::v1::CheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Check_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::CheckResponse>* OpenFGAService::Stub::AsyncCheckRaw(::grpc::ClientContext* context, const ::openfga::v1::CheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::BatchCheck(::grpc::ClientContext* context, const ::openfga::v1::BatchCheckRequest& request, ::openfga::v1::BatchCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::BatchCheckRequest, ::openfga::v1::BatchCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchCheck_, context, request, response);
}

void OpenFGAService::Stub::async::BatchCheck(::grpc::ClientContext* context, const ::openfga::v1::BatchCheckRequest* request, ::openfga::v1::BatchCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::BatchCheckRequest, ::openfga::v1::BatchCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchCheck_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::BatchCheck(::grpc::ClientContext* context, const ::openfga::v1::BatchCheckRequest* request, ::openfga::v1::BatchCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::BatchCheckResponse>* OpenFGAService::Stub::PrepareAsyncBatchCheckRaw(::grpc::ClientContext* context, const ::openfga::v1::BatchCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::BatchCheckResponse, ::openfga::v1::BatchCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::BatchCheckResponse>* OpenFGAService::Stub::AsyncBatchCheckRaw(::grpc::ClientContext* context, const ::openfga::v1::BatchCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::Expand(::grpc::ClientContext* context, const ::openfga::v1::ExpandRequest& request, ::openfga::v1::ExpandResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::ExpandRequest, ::openfga::v1::ExpandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Expand_, context, request, response);
}

void OpenFGAService::Stub::async::Expand(::grpc::ClientContext* context, const ::openfga::v1::ExpandRequest* request, ::openfga::v1::ExpandResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::ExpandRequest, ::openfga::v1::ExpandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Expand_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::Expand(::grpc::ClientContext* context, const ::openfga::v1::ExpandRequest* request, ::openfga::v1::ExpandResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Expand_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ExpandResponse>* OpenFGAService::Stub::PrepareAsyncExpandRaw(::grpc::ClientContext* context, const ::openfga::v1::ExpandRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::ExpandResponse, ::openfga::v1::ExpandRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Expand_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ExpandResponse>* OpenFGAService::Stub::AsyncExpandRaw(::grpc::ClientContext* context, const ::openfga::v1::ExpandRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExpandRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::ReadAuthorizationModels(::grpc::ClientContext* context, const ::openfga::v1::ReadAuthorizationModelsRequest& request, ::openfga::v1::ReadAuthorizationModelsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::ReadAuthorizationModelsRequest, ::openfga::v1::ReadAuthorizationModelsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadAuthorizationModels_, context, request, response);
}

void OpenFGAService::Stub::async::ReadAuthorizationModels(::grpc::ClientContext* context, const ::openfga::v1::ReadAuthorizationModelsRequest* request, ::openfga::v1::ReadAuthorizationModelsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::ReadAuthorizationModelsRequest, ::openfga::v1::ReadAuthorizationModelsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadAuthorizationModels_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::ReadAuthorizationModels(::grpc::ClientContext* context, const ::openfga::v1::ReadAuthorizationModelsRequest* request, ::openfga::v1::ReadAuthorizationModelsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadAuthorizationModels_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ReadAuthorizationModelsResponse>* OpenFGAService::Stub::PrepareAsyncReadAuthorizationModelsRaw(::grpc::ClientContext* context, const ::openfga::v1::ReadAuthorizationModelsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::ReadAuthorizationModelsResponse, ::openfga::v1::ReadAuthorizationModelsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadAuthorizationModels_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ReadAuthorizationModelsResponse>* OpenFGAService::Stub::AsyncReadAuthorizationModelsRaw(::grpc::ClientContext* context, const ::openfga::v1::ReadAuthorizationModelsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadAuthorizationModelsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::ReadAuthorizationModel(::grpc::ClientContext* context, const ::openfga::v1::ReadAuthorizationModelRequest& request, ::openfga::v1::ReadAuthorizationModelResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::ReadAuthorizationModelRequest, ::openfga::v1::ReadAuthorizationModelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadAuthorizationModel_, context, request, response);
}

void OpenFGAService::Stub::async::ReadAuthorizationModel(::grpc::ClientContext* context, const ::openfga::v1::ReadAuthorizationModelRequest* request, ::openfga::v1::ReadAuthorizationModelResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::ReadAuthorizationModelRequest, ::openfga::v1::ReadAuthorizationModelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadAuthorizationModel_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::ReadAuthorizationModel(::grpc::ClientContext* context, const ::openfga::v1::ReadAuthorizationModelRequest* request, ::openfga::v1::ReadAuthorizationModelResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadAuthorizationModel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ReadAuthorizationModelResponse>* OpenFGAService::Stub::PrepareAsyncReadAuthorizationModelRaw(::grpc::ClientContext* context, const ::openfga::v1::ReadAuthorizationModelRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::ReadAuthorizationModelResponse, ::openfga::v1::ReadAuthorizationModelRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadAuthorizationModel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ReadAuthorizationModelResponse>* OpenFGAService::Stub::AsyncReadAuthorizationModelRaw(::grpc::ClientContext* context, const ::openfga::v1::ReadAuthorizationModelRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadAuthorizationModelRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::WriteAuthorizationModel(::grpc::ClientContext* context, const ::openfga::v1::WriteAuthorizationModelRequest& request, ::openfga::v1::WriteAuthorizationModelResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::WriteAuthorizationModelRequest, ::openfga::v1::WriteAuthorizationModelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_WriteAuthorizationModel_, context, request, response);
}

void OpenFGAService::Stub::async::WriteAuthorizationModel(::grpc::ClientContext* context, const ::openfga::v1::WriteAuthorizationModelRequest* request, ::openfga::v1::WriteAuthorizationModelResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::WriteAuthorizationModelRequest, ::openfga::v1::WriteAuthorizationModelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteAuthorizationModel_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::WriteAuthorizationModel(::grpc::ClientContext* context, const ::openfga::v1::WriteAuthorizationModelRequest* request, ::openfga::v1::WriteAuthorizationModelResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteAuthorizationModel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::WriteAuthorizationModelResponse>* OpenFGAService::Stub::PrepareAsyncWriteAuthorizationModelRaw(::grpc::ClientContext* context, const ::openfga::v1::WriteAuthorizationModelRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::WriteAuthorizationModelResponse, ::openfga::v1::WriteAuthorizationModelRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_WriteAuthorizationModel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::WriteAuthorizationModelResponse>* OpenFGAService::Stub::AsyncWriteAuthorizationModelRaw(::grpc::ClientContext* context, const ::openfga::v1::WriteAuthorizationModelRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWriteAuthorizationModelRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::WriteAssertions(::grpc::ClientContext* context, const ::openfga::v1::WriteAssertionsRequest& request, ::openfga::v1::WriteAssertionsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::WriteAssertionsRequest, ::openfga::v1::WriteAssertionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_WriteAssertions_, context, request, response);
}

void OpenFGAService::Stub::async::WriteAssertions(::grpc::ClientContext* context, const ::openfga::v1::WriteAssertionsRequest* request, ::openfga::v1::WriteAssertionsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::WriteAssertionsRequest, ::openfga::v1::WriteAssertionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteAssertions_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::WriteAssertions(::grpc::ClientContext* context, const ::openfga::v1::WriteAssertionsRequest* request, ::openfga::v1::WriteAssertionsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteAssertions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::WriteAssertionsResponse>* OpenFGAService::Stub::PrepareAsyncWriteAssertionsRaw(::grpc::ClientContext* context, const ::openfga::v1::WriteAssertionsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::WriteAssertionsResponse, ::openfga::v1::WriteAssertionsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_WriteAssertions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::WriteAssertionsResponse>* OpenFGAService::Stub::AsyncWriteAssertionsRaw(::grpc::ClientContext* context, const ::openfga::v1::WriteAssertionsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWriteAssertionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::ReadAssertions(::grpc::ClientContext* context, const ::openfga::v1::ReadAssertionsRequest& request, ::openfga::v1::ReadAssertionsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::ReadAssertionsRequest, ::openfga::v1::ReadAssertionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadAssertions_, context, request, response);
}

void OpenFGAService::Stub::async::ReadAssertions(::grpc::ClientContext* context, const ::openfga::v1::ReadAssertionsRequest* request, ::openfga::v1::ReadAssertionsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::ReadAssertionsRequest, ::openfga::v1::ReadAssertionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadAssertions_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::ReadAssertions(::grpc::ClientContext* context, const ::openfga::v1::ReadAssertionsRequest* request, ::openfga::v1::ReadAssertionsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadAssertions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ReadAssertionsResponse>* OpenFGAService::Stub::PrepareAsyncReadAssertionsRaw(::grpc::ClientContext* context, const ::openfga::v1::ReadAssertionsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::ReadAssertionsResponse, ::openfga::v1::ReadAssertionsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadAssertions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ReadAssertionsResponse>* OpenFGAService::Stub::AsyncReadAssertionsRaw(::grpc::ClientContext* context, const ::openfga::v1::ReadAssertionsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadAssertionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::ReadChanges(::grpc::ClientContext* context, const ::openfga::v1::ReadChangesRequest& request, ::openfga::v1::ReadChangesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::ReadChangesRequest, ::openfga::v1::ReadChangesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadChanges_, context, request, response);
}

void OpenFGAService::Stub::async::ReadChanges(::grpc::ClientContext* context, const ::openfga::v1::ReadChangesRequest* request, ::openfga::v1::ReadChangesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::ReadChangesRequest, ::openfga::v1::ReadChangesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadChanges_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::ReadChanges(::grpc::ClientContext* context, const ::openfga::v1::ReadChangesRequest* request, ::openfga::v1::ReadChangesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadChanges_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ReadChangesResponse>* OpenFGAService::Stub::PrepareAsyncReadChangesRaw(::grpc::ClientContext* context, const ::openfga::v1::ReadChangesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::ReadChangesResponse, ::openfga::v1::ReadChangesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadChanges_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ReadChangesResponse>* OpenFGAService::Stub::AsyncReadChangesRaw(::grpc::ClientContext* context, const ::openfga::v1::ReadChangesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadChangesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::CreateStore(::grpc::ClientContext* context, const ::openfga::v1::CreateStoreRequest& request, ::openfga::v1::CreateStoreResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::CreateStoreRequest, ::openfga::v1::CreateStoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateStore_, context, request, response);
}

void OpenFGAService::Stub::async::CreateStore(::grpc::ClientContext* context, const ::openfga::v1::CreateStoreRequest* request, ::openfga::v1::CreateStoreResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::CreateStoreRequest, ::openfga::v1::CreateStoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateStore_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::CreateStore(::grpc::ClientContext* context, const ::openfga::v1::CreateStoreRequest* request, ::openfga::v1::CreateStoreResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateStore_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::CreateStoreResponse>* OpenFGAService::Stub::PrepareAsyncCreateStoreRaw(::grpc::ClientContext* context, const ::openfga::v1::CreateStoreRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::CreateStoreResponse, ::openfga::v1::CreateStoreRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateStore_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::CreateStoreResponse>* OpenFGAService::Stub::AsyncCreateStoreRaw(::grpc::ClientContext* context, const ::openfga::v1::CreateStoreRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateStoreRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::UpdateStore(::grpc::ClientContext* context, const ::openfga::v1::UpdateStoreRequest& request, ::openfga::v1::UpdateStoreResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::UpdateStoreRequest, ::openfga::v1::UpdateStoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateStore_, context, request, response);
}

void OpenFGAService::Stub::async::UpdateStore(::grpc::ClientContext* context, const ::openfga::v1::UpdateStoreRequest* request, ::openfga::v1::UpdateStoreResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::UpdateStoreRequest, ::openfga::v1::UpdateStoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateStore_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::UpdateStore(::grpc::ClientContext* context, const ::openfga::v1::UpdateStoreRequest* request, ::openfga::v1::UpdateStoreResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateStore_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::UpdateStoreResponse>* OpenFGAService::Stub::PrepareAsyncUpdateStoreRaw(::grpc::ClientContext* context, const ::openfga::v1::UpdateStoreRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::UpdateStoreResponse, ::openfga::v1::UpdateStoreRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateStore_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::UpdateStoreResponse>* OpenFGAService::Stub::AsyncUpdateStoreRaw(::grpc::ClientContext* context, const ::openfga::v1::UpdateStoreRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateStoreRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::DeleteStore(::grpc::ClientContext* context, const ::openfga::v1::DeleteStoreRequest& request, ::openfga::v1::DeleteStoreResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::DeleteStoreRequest, ::openfga::v1::DeleteStoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteStore_, context, request, response);
}

void OpenFGAService::Stub::async::DeleteStore(::grpc::ClientContext* context, const ::openfga::v1::DeleteStoreRequest* request, ::openfga::v1::DeleteStoreResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::DeleteStoreRequest, ::openfga::v1::DeleteStoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteStore_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::DeleteStore(::grpc::ClientContext* context, const ::openfga::v1::DeleteStoreRequest* request, ::openfga::v1::DeleteStoreResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteStore_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::DeleteStoreResponse>* OpenFGAService::Stub::PrepareAsyncDeleteStoreRaw(::grpc::ClientContext* context, const ::openfga::v1::DeleteStoreRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::DeleteStoreResponse, ::openfga::v1::DeleteStoreRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteStore_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::DeleteStoreResponse>* OpenFGAService::Stub::AsyncDeleteStoreRaw(::grpc::ClientContext* context, const ::openfga::v1::DeleteStoreRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteStoreRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::GetStore(::grpc::ClientContext* context, const ::openfga::v1::GetStoreRequest& request, ::openfga::v1::GetStoreResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::GetStoreRequest, ::openfga::v1::GetStoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStore_, context, request, response);
}

void OpenFGAService::Stub::async::GetStore(::grpc::ClientContext* context, const ::openfga::v1::GetStoreRequest* request, ::openfga::v1::GetStoreResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::GetStoreRequest, ::openfga::v1::GetStoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStore_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::GetStore(::grpc::ClientContext* context, const ::openfga::v1::GetStoreRequest* request, ::openfga::v1::GetStoreResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStore_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::GetStoreResponse>* OpenFGAService::Stub::PrepareAsyncGetStoreRaw(::grpc::ClientContext* context, const ::openfga::v1::GetStoreRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::GetStoreResponse, ::openfga::v1::GetStoreRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStore_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::GetStoreResponse>* OpenFGAService::Stub::AsyncGetStoreRaw(::grpc::ClientContext* context, const ::openfga::v1::GetStoreRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStoreRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::ListStores(::grpc::ClientContext* context, const ::openfga::v1::ListStoresRequest& request, ::openfga::v1::ListStoresResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::ListStoresRequest, ::openfga::v1::ListStoresResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListStores_, context, request, response);
}

void OpenFGAService::Stub::async::ListStores(::grpc::ClientContext* context, const ::openfga::v1::ListStoresRequest* request, ::openfga::v1::ListStoresResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::ListStoresRequest, ::openfga::v1::ListStoresResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListStores_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::ListStores(::grpc::ClientContext* context, const ::openfga::v1::ListStoresRequest* request, ::openfga::v1::ListStoresResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListStores_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ListStoresResponse>* OpenFGAService::Stub::PrepareAsyncListStoresRaw(::grpc::ClientContext* context, const ::openfga::v1::ListStoresRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::ListStoresResponse, ::openfga::v1::ListStoresRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListStores_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ListStoresResponse>* OpenFGAService::Stub::AsyncListStoresRaw(::grpc::ClientContext* context, const ::openfga::v1::ListStoresRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListStoresRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::openfga::v1::StreamedListObjectsResponse>* OpenFGAService::Stub::StreamedListObjectsRaw(::grpc::ClientContext* context, const ::openfga::v1::StreamedListObjectsRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::openfga::v1::StreamedListObjectsResponse>::Create(channel_.get(), rpcmethod_StreamedListObjects_, context, request);
}

void OpenFGAService::Stub::async::StreamedListObjects(::grpc::ClientContext* context, const ::openfga::v1::StreamedListObjectsRequest* request, ::grpc::ClientReadReactor< ::openfga::v1::StreamedListObjectsResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::openfga::v1::StreamedListObjectsResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamedListObjects_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::openfga::v1::StreamedListObjectsResponse>* OpenFGAService::Stub::AsyncStreamedListObjectsRaw(::grpc::ClientContext* context, const ::openfga::v1::StreamedListObjectsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::openfga::v1::StreamedListObjectsResponse>::Create(channel_.get(), cq, rpcmethod_StreamedListObjects_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::openfga::v1::StreamedListObjectsResponse>* OpenFGAService::Stub::PrepareAsyncStreamedListObjectsRaw(::grpc::ClientContext* context, const ::openfga::v1::StreamedListObjectsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::openfga::v1::StreamedListObjectsResponse>::Create(channel_.get(), cq, rpcmethod_StreamedListObjects_, context, request, false, nullptr);
}

::grpc::Status OpenFGAService::Stub::ListObjects(::grpc::ClientContext* context, const ::openfga::v1::ListObjectsRequest& request, ::openfga::v1::ListObjectsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::ListObjectsRequest, ::openfga::v1::ListObjectsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListObjects_, context, request, response);
}

void OpenFGAService::Stub::async::ListObjects(::grpc::ClientContext* context, const ::openfga::v1::ListObjectsRequest* request, ::openfga::v1::ListObjectsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::ListObjectsRequest, ::openfga::v1::ListObjectsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListObjects_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::ListObjects(::grpc::ClientContext* context, const ::openfga::v1::ListObjectsRequest* request, ::openfga::v1::ListObjectsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListObjects_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ListObjectsResponse>* OpenFGAService::Stub::PrepareAsyncListObjectsRaw(::grpc::ClientContext* context, const ::openfga::v1::ListObjectsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::ListObjectsResponse, ::openfga::v1::ListObjectsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListObjects_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ListObjectsResponse>* OpenFGAService::Stub::AsyncListObjectsRaw(::grpc::ClientContext* context, const ::openfga::v1::ListObjectsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListObjectsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OpenFGAService::Stub::ListUsers(::grpc::ClientContext* context, const ::openfga::v1::ListUsersRequest& request, ::openfga::v1::ListUsersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openfga::v1::ListUsersRequest, ::openfga::v1::ListUsersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListUsers_, context, request, response);
}

void OpenFGAService::Stub::async::ListUsers(::grpc::ClientContext* context, const ::openfga::v1::ListUsersRequest* request, ::openfga::v1::ListUsersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openfga::v1::ListUsersRequest, ::openfga::v1::ListUsersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListUsers_, context, request, response, std::move(f));
}

void OpenFGAService::Stub::async::ListUsers(::grpc::ClientContext* context, const ::openfga::v1::ListUsersRequest* request, ::openfga::v1::ListUsersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListUsers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ListUsersResponse>* OpenFGAService::Stub::PrepareAsyncListUsersRaw(::grpc::ClientContext* context, const ::openfga::v1::ListUsersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openfga::v1::ListUsersResponse, ::openfga::v1::ListUsersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListUsers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openfga::v1::ListUsersResponse>* OpenFGAService::Stub::AsyncListUsersRaw(::grpc::ClientContext* context, const ::openfga::v1::ListUsersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListUsersRaw(context, request, cq);
  result->StartCall();
  return result;
}

OpenFGAService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::ReadRequest, ::openfga::v1::ReadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::ReadRequest* req,
             ::openfga::v1::ReadResponse* resp) {
               return service->Read(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::WriteRequest, ::openfga::v1::WriteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::WriteRequest* req,
             ::openfga::v1::WriteResponse* resp) {
               return service->Write(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::CheckRequest, ::openfga::v1::CheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::CheckRequest* req,
             ::openfga::v1::CheckResponse* resp) {
               return service->Check(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::BatchCheckRequest, ::openfga::v1::BatchCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::BatchCheckRequest* req,
             ::openfga::v1::BatchCheckResponse* resp) {
               return service->BatchCheck(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::ExpandRequest, ::openfga::v1::ExpandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::ExpandRequest* req,
             ::openfga::v1::ExpandResponse* resp) {
               return service->Expand(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::ReadAuthorizationModelsRequest, ::openfga::v1::ReadAuthorizationModelsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::ReadAuthorizationModelsRequest* req,
             ::openfga::v1::ReadAuthorizationModelsResponse* resp) {
               return service->ReadAuthorizationModels(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::ReadAuthorizationModelRequest, ::openfga::v1::ReadAuthorizationModelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::ReadAuthorizationModelRequest* req,
             ::openfga::v1::ReadAuthorizationModelResponse* resp) {
               return service->ReadAuthorizationModel(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::WriteAuthorizationModelRequest, ::openfga::v1::WriteAuthorizationModelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::WriteAuthorizationModelRequest* req,
             ::openfga::v1::WriteAuthorizationModelResponse* resp) {
               return service->WriteAuthorizationModel(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::WriteAssertionsRequest, ::openfga::v1::WriteAssertionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::WriteAssertionsRequest* req,
             ::openfga::v1::WriteAssertionsResponse* resp) {
               return service->WriteAssertions(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::ReadAssertionsRequest, ::openfga::v1::ReadAssertionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::ReadAssertionsRequest* req,
             ::openfga::v1::ReadAssertionsResponse* resp) {
               return service->ReadAssertions(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::ReadChangesRequest, ::openfga::v1::ReadChangesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::ReadChangesRequest* req,
             ::openfga::v1::ReadChangesResponse* resp) {
               return service->ReadChanges(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::CreateStoreRequest, ::openfga::v1::CreateStoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::CreateStoreRequest* req,
             ::openfga::v1::CreateStoreResponse* resp) {
               return service->CreateStore(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::UpdateStoreRequest, ::openfga::v1::UpdateStoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::UpdateStoreRequest* req,
             ::openfga::v1::UpdateStoreResponse* resp) {
               return service->UpdateStore(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::DeleteStoreRequest, ::openfga::v1::DeleteStoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::DeleteStoreRequest* req,
             ::openfga::v1::DeleteStoreResponse* resp) {
               return service->DeleteStore(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::GetStoreRequest, ::openfga::v1::GetStoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::GetStoreRequest* req,
             ::openfga::v1::GetStoreResponse* resp) {
               return service->GetStore(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::ListStoresRequest, ::openfga::v1::ListStoresResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::ListStoresRequest* req,
             ::openfga::v1::ListStoresResponse* resp) {
               return service->ListStores(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[16],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< OpenFGAService::Service, ::openfga::v1::StreamedListObjectsRequest, ::openfga::v1::StreamedListObjectsResponse>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::StreamedListObjectsRequest* req,
             ::grpc::ServerWriter<::openfga::v1::StreamedListObjectsResponse>* writer) {
               return service->StreamedListObjects(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::ListObjectsRequest, ::openfga::v1::ListObjectsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::ListObjectsRequest* req,
             ::openfga::v1::ListObjectsResponse* resp) {
               return service->ListObjects(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OpenFGAService_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OpenFGAService::Service, ::openfga::v1::ListUsersRequest, ::openfga::v1::ListUsersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OpenFGAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openfga::v1::ListUsersRequest* req,
             ::openfga::v1::ListUsersResponse* resp) {
               return service->ListUsers(ctx, req, resp);
             }, this)));
}

OpenFGAService::Service::~Service() {
}

::grpc::Status OpenFGAService::Service::Read(::grpc::ServerContext* context, const ::openfga::v1::ReadRequest* request, ::openfga::v1::ReadResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::Write(::grpc::ServerContext* context, const ::openfga::v1::WriteRequest* request, ::openfga::v1::WriteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::Check(::grpc::ServerContext* context, const ::openfga::v1::CheckRequest* request, ::openfga::v1::CheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::BatchCheck(::grpc::ServerContext* context, const ::openfga::v1::BatchCheckRequest* request, ::openfga::v1::BatchCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::Expand(::grpc::ServerContext* context, const ::openfga::v1::ExpandRequest* request, ::openfga::v1::ExpandResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::ReadAuthorizationModels(::grpc::ServerContext* context, const ::openfga::v1::ReadAuthorizationModelsRequest* request, ::openfga::v1::ReadAuthorizationModelsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::ReadAuthorizationModel(::grpc::ServerContext* context, const ::openfga::v1::ReadAuthorizationModelRequest* request, ::openfga::v1::ReadAuthorizationModelResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::WriteAuthorizationModel(::grpc::ServerContext* context, const ::openfga::v1::WriteAuthorizationModelRequest* request, ::openfga::v1::WriteAuthorizationModelResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::WriteAssertions(::grpc::ServerContext* context, const ::openfga::v1::WriteAssertionsRequest* request, ::openfga::v1::WriteAssertionsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::ReadAssertions(::grpc::ServerContext* context, const ::openfga::v1::ReadAssertionsRequest* request, ::openfga::v1::ReadAssertionsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::ReadChanges(::grpc::ServerContext* context, const ::openfga::v1::ReadChangesRequest* request, ::openfga::v1::ReadChangesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::CreateStore(::grpc::ServerContext* context, const ::openfga::v1::CreateStoreRequest* request, ::openfga::v1::CreateStoreResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::UpdateStore(::grpc::ServerContext* context, const ::openfga::v1::UpdateStoreRequest* request, ::openfga::v1::UpdateStoreResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::DeleteStore(::grpc::ServerContext* context, const ::openfga::v1::DeleteStoreRequest* request, ::openfga::v1::DeleteStoreResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::GetStore(::grpc::ServerContext* context, const ::openfga::v1::GetStoreRequest* request, ::openfga::v1::GetStoreResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::ListStores(::grpc::ServerContext* context, const ::openfga::v1::ListStoresRequest* request, ::openfga::v1::ListStoresResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::StreamedListObjects(::grpc::ServerContext* context, const ::openfga::v1::StreamedListObjectsRequest* request, ::grpc::ServerWriter< ::openfga::v1::StreamedListObjectsResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::ListObjects(::grpc::ServerContext* context, const ::openfga::v1::ListObjectsRequest* request, ::openfga::v1::ListObjectsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OpenFGAService::Service::ListUsers(::grpc::ServerContext* context, const ::openfga::v1::ListUsersRequest* request, ::openfga::v1::ListUsersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace openfga
}  // namespace v1

