// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openfga/v1/openfga_service_consistency.proto

#include "openfga/v1/openfga_service_consistency.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace openfga {
namespace v1 {
}  // namespace v1
}  // namespace openfga
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto = nullptr;
const uint32_t TableStruct_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n,openfga/v1/openfga_service_consistency"
  ".proto\022\nopenfga.v1*W\n\025ConsistencyPrefere"
  "nce\022\017\n\013UNSPECIFIED\020\000\022\024\n\020MINIMIZE_LATENCY"
  "\020d\022\027\n\022HIGHER_CONSISTENCY\020\310\001By\n\016com.openf"
  "ga.v1B\036OpenfgaServiceConsistencyProtoP\001\242"
  "\002\003OXX\252\002\nOpenfga.V1\312\002\nOpenfga\\V1\342\002\026Openfg"
  "a\\V1\\GPBMetadata\352\002\013Openfga::V1b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto = {
    false, false, 278, descriptor_table_protodef_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto,
    "openfga/v1/openfga_service_consistency.proto",
    &descriptor_table_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto::offsets,
    nullptr, file_level_enum_descriptors_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto,
    file_level_service_descriptors_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto_getter() {
  return &descriptor_table_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto(&descriptor_table_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto);
namespace openfga {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ConsistencyPreference_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto);
  return file_level_enum_descriptors_openfga_2fv1_2fopenfga_5fservice_5fconsistency_2eproto[0];
}
bool ConsistencyPreference_IsValid(int value) {
  switch (value) {
    case 0:
    case 100:
    case 200:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace openfga
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
