// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openfga/v1/openapi.proto

#include "openfga/v1/openapi.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace openfga {
namespace v1 {
}  // namespace v1
}  // namespace openfga
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_openfga_2fv1_2fopenapi_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_openfga_2fv1_2fopenapi_2eproto = nullptr;
const uint32_t TableStruct_openfga_2fv1_2fopenapi_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_openfga_2fv1_2fopenapi_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030openfga/v1/openapi.proto\022\nopenfga.v1\032."
  "protoc-gen-openapiv2/options/annotations"
  ".protoB\220\010\n\016com.openfga.v1B\014OpenapiProtoP"
  "\001\242\002\003OXX\252\002\nOpenfga.V1\312\002\nOpenfga\\V1\342\002\026Open"
  "fga\\V1\\GPBMetadata\352\002\013Openfga::V1\222A\245\007\022\200\002\n"
  "\007OpenFGA\022uA high performance and flexibl"
  "e authorization/permission engine built "
  "for developers and inspired by Google Za"
  "nzibar.\"5\n\007OpenFGA\022\023https://openfga.dev\032"
  "\025community@openfga.dev*B\n\nApache-2.0\0224ht"
  "tps://github.com/openfga/openfga/blob/ma"
  "in/LICENSE2\0031.x*\001\0022\020application/json:\020ap"
  "plication/jsonR]\n\003400\022V\n$Request failed "
  "due to invalid input.\022.\n,\032*.openfga.v1.V"
  "alidationErrorMessageResponseRD\n\003401\022=\n\022"
  "Not authenticated.\022\'\n%\032#.openfga.v1.Unau"
  "thenticatedResponseR6\n\003403\022/\n\nForbidden."
  "\022!\n\037\032\035.openfga.v1.ForbiddenResponseR_\n\0034"
  "04\022X\n%Request failed due to incorrect pa"
  "th.\022/\n-\032+.openfga.v1.PathUnknownErrorMes"
  "sageResponseR`\n\003409\022Y\n/Request was abort"
  "ed due a transaction conflict.\022&\n$\032\".ope"
  "nfga.v1.AbortedMessageResponseRt\n\003422\022m\n"
  "6Request timed out due to excessive requ"
  "est throttling.\0223\n1\032/.openfga.v1.Unproce"
  "ssableContentMessageResponseRc\n\003500\022\\\n,R"
  "equest failed due to internal server err"
  "or.\022,\n*\032(.openfga.v1.InternalErrorMessag"
  "eResponseb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_openfga_2fv1_2fopenapi_2eproto_deps[1] = {
  &::descriptor_table_protoc_2dgen_2dopenapiv2_2foptions_2fannotations_2eproto,
};
static ::_pbi::once_flag descriptor_table_openfga_2fv1_2fopenapi_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_openfga_2fv1_2fopenapi_2eproto = {
    false, false, 1137, descriptor_table_protodef_openfga_2fv1_2fopenapi_2eproto,
    "openfga/v1/openapi.proto",
    &descriptor_table_openfga_2fv1_2fopenapi_2eproto_once, descriptor_table_openfga_2fv1_2fopenapi_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_openfga_2fv1_2fopenapi_2eproto::offsets,
    nullptr, file_level_enum_descriptors_openfga_2fv1_2fopenapi_2eproto,
    file_level_service_descriptors_openfga_2fv1_2fopenapi_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_openfga_2fv1_2fopenapi_2eproto_getter() {
  return &descriptor_table_openfga_2fv1_2fopenapi_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_openfga_2fv1_2fopenapi_2eproto(&descriptor_table_openfga_2fv1_2fopenapi_2eproto);
namespace openfga {
namespace v1 {

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace openfga
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
