// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bytestream/bytestream.proto

#include "google/bytestream/bytestream.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace google {
namespace bytestream {
PROTOBUF_CONSTEXPR ReadRequest::ReadRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.resource_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.read_offset_)*/int64_t{0}
  , /*decltype(_impl_.read_limit_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReadRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadRequestDefaultTypeInternal() {}
  union {
    ReadRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadRequestDefaultTypeInternal _ReadRequest_default_instance_;
PROTOBUF_CONSTEXPR ReadResponse::ReadResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReadResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadResponseDefaultTypeInternal() {}
  union {
    ReadResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadResponseDefaultTypeInternal _ReadResponse_default_instance_;
PROTOBUF_CONSTEXPR WriteRequest::WriteRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.resource_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.write_offset_)*/int64_t{0}
  , /*decltype(_impl_.finish_write_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct WriteRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WriteRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WriteRequestDefaultTypeInternal() {}
  union {
    WriteRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WriteRequestDefaultTypeInternal _WriteRequest_default_instance_;
PROTOBUF_CONSTEXPR WriteResponse::WriteResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.committed_size_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct WriteResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WriteResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WriteResponseDefaultTypeInternal() {}
  union {
    WriteResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WriteResponseDefaultTypeInternal _WriteResponse_default_instance_;
PROTOBUF_CONSTEXPR QueryWriteStatusRequest::QueryWriteStatusRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.resource_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct QueryWriteStatusRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QueryWriteStatusRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~QueryWriteStatusRequestDefaultTypeInternal() {}
  union {
    QueryWriteStatusRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QueryWriteStatusRequestDefaultTypeInternal _QueryWriteStatusRequest_default_instance_;
PROTOBUF_CONSTEXPR QueryWriteStatusResponse::QueryWriteStatusResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.committed_size_)*/int64_t{0}
  , /*decltype(_impl_.complete_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct QueryWriteStatusResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QueryWriteStatusResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~QueryWriteStatusResponseDefaultTypeInternal() {}
  union {
    QueryWriteStatusResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QueryWriteStatusResponseDefaultTypeInternal _QueryWriteStatusResponse_default_instance_;
}  // namespace bytestream
}  // namespace google
static ::_pb::Metadata file_level_metadata_google_2fbytestream_2fbytestream_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_google_2fbytestream_2fbytestream_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_google_2fbytestream_2fbytestream_2eproto = nullptr;

const uint32_t TableStruct_google_2fbytestream_2fbytestream_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::bytestream::ReadRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::bytestream::ReadRequest, _impl_.resource_name_),
  PROTOBUF_FIELD_OFFSET(::google::bytestream::ReadRequest, _impl_.read_offset_),
  PROTOBUF_FIELD_OFFSET(::google::bytestream::ReadRequest, _impl_.read_limit_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::bytestream::ReadResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::bytestream::ReadResponse, _impl_.data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::bytestream::WriteRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::bytestream::WriteRequest, _impl_.resource_name_),
  PROTOBUF_FIELD_OFFSET(::google::bytestream::WriteRequest, _impl_.write_offset_),
  PROTOBUF_FIELD_OFFSET(::google::bytestream::WriteRequest, _impl_.finish_write_),
  PROTOBUF_FIELD_OFFSET(::google::bytestream::WriteRequest, _impl_.data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::bytestream::WriteResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::bytestream::WriteResponse, _impl_.committed_size_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::bytestream::QueryWriteStatusRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::bytestream::QueryWriteStatusRequest, _impl_.resource_name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::bytestream::QueryWriteStatusResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::bytestream::QueryWriteStatusResponse, _impl_.committed_size_),
  PROTOBUF_FIELD_OFFSET(::google::bytestream::QueryWriteStatusResponse, _impl_.complete_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::google::bytestream::ReadRequest)},
  { 9, -1, -1, sizeof(::google::bytestream::ReadResponse)},
  { 16, -1, -1, sizeof(::google::bytestream::WriteRequest)},
  { 26, -1, -1, sizeof(::google::bytestream::WriteResponse)},
  { 33, -1, -1, sizeof(::google::bytestream::QueryWriteStatusRequest)},
  { 40, -1, -1, sizeof(::google::bytestream::QueryWriteStatusResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::google::bytestream::_ReadRequest_default_instance_._instance,
  &::google::bytestream::_ReadResponse_default_instance_._instance,
  &::google::bytestream::_WriteRequest_default_instance_._instance,
  &::google::bytestream::_WriteResponse_default_instance_._instance,
  &::google::bytestream::_QueryWriteStatusRequest_default_instance_._instance,
  &::google::bytestream::_QueryWriteStatusResponse_default_instance_._instance,
};

const char descriptor_table_protodef_google_2fbytestream_2fbytestream_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\"google/bytestream/bytestream.proto\022\021go"
  "ogle.bytestream\"r\n\013ReadRequest\022#\n\rresour"
  "ce_name\030\001 \001(\tR\014resourceName\022\037\n\013read_offs"
  "et\030\002 \001(\003R\nreadOffset\022\035\n\nread_limit\030\003 \001(\003"
  "R\treadLimit\"\"\n\014ReadResponse\022\022\n\004data\030\n \001("
  "\014R\004data\"\215\001\n\014WriteRequest\022#\n\rresource_nam"
  "e\030\001 \001(\tR\014resourceName\022!\n\014write_offset\030\002 "
  "\001(\003R\013writeOffset\022!\n\014finish_write\030\003 \001(\010R\013"
  "finishWrite\022\022\n\004data\030\n \001(\014R\004data\"6\n\rWrite"
  "Response\022%\n\016committed_size\030\001 \001(\003R\rcommit"
  "tedSize\">\n\027QueryWriteStatusRequest\022#\n\rre"
  "source_name\030\001 \001(\tR\014resourceName\"]\n\030Query"
  "WriteStatusResponse\022%\n\016committed_size\030\001 "
  "\001(\003R\rcommittedSize\022\032\n\010complete\030\002 \001(\010R\010co"
  "mplete2\222\002\n\nByteStream\022I\n\004Read\022\036.google.b"
  "ytestream.ReadRequest\032\037.google.bytestrea"
  "m.ReadResponse0\001\022L\n\005Write\022\037.google.bytes"
  "tream.WriteRequest\032 .google.bytestream.W"
  "riteResponse(\001\022k\n\020QueryWriteStatus\022*.goo"
  "gle.bytestream.QueryWriteStatusRequest\032+"
  ".google.bytestream.QueryWriteStatusRespo"
  "nseB\312\001\n\025com.google.bytestreamB\017Bytestrea"
  "mProtoP\001Z;google.golang.org/genproto/goo"
  "gleapis/bytestream;bytestream\242\002\003GBX\252\002\021Go"
  "ogle.Bytestream\312\002\021Google\\Bytestream\342\002\035Go"
  "ogle\\Bytestream\\GPBMetadata\352\002\022Google::By"
  "testreamb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_google_2fbytestream_2fbytestream_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_google_2fbytestream_2fbytestream_2eproto = {
    false, false, 1056, descriptor_table_protodef_google_2fbytestream_2fbytestream_2eproto,
    "google/bytestream/bytestream.proto",
    &descriptor_table_google_2fbytestream_2fbytestream_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_google_2fbytestream_2fbytestream_2eproto::offsets,
    file_level_metadata_google_2fbytestream_2fbytestream_2eproto, file_level_enum_descriptors_google_2fbytestream_2fbytestream_2eproto,
    file_level_service_descriptors_google_2fbytestream_2fbytestream_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_google_2fbytestream_2fbytestream_2eproto_getter() {
  return &descriptor_table_google_2fbytestream_2fbytestream_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_google_2fbytestream_2fbytestream_2eproto(&descriptor_table_google_2fbytestream_2fbytestream_2eproto);
namespace google {
namespace bytestream {

// ===================================================================

class ReadRequest::_Internal {
 public:
};

ReadRequest::ReadRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.bytestream.ReadRequest)
}
ReadRequest::ReadRequest(const ReadRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ReadRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_name_){}
    , decltype(_impl_.read_offset_){}
    , decltype(_impl_.read_limit_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.resource_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.resource_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_resource_name().empty()) {
    _this->_impl_.resource_name_.Set(from._internal_resource_name(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.read_offset_, &from._impl_.read_offset_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.read_limit_) -
    reinterpret_cast<char*>(&_impl_.read_offset_)) + sizeof(_impl_.read_limit_));
  // @@protoc_insertion_point(copy_constructor:google.bytestream.ReadRequest)
}

inline void ReadRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_name_){}
    , decltype(_impl_.read_offset_){int64_t{0}}
    , decltype(_impl_.read_limit_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.resource_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.resource_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ReadRequest::~ReadRequest() {
  // @@protoc_insertion_point(destructor:google.bytestream.ReadRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ReadRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.resource_name_.Destroy();
}

void ReadRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ReadRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:google.bytestream.ReadRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.resource_name_.ClearToEmpty();
  ::memset(&_impl_.read_offset_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.read_limit_) -
      reinterpret_cast<char*>(&_impl_.read_offset_)) + sizeof(_impl_.read_limit_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReadRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string resource_name = 1 [json_name = "resourceName"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_resource_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "google.bytestream.ReadRequest.resource_name"));
        } else
          goto handle_unusual;
        continue;
      // int64 read_offset = 2 [json_name = "readOffset"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.read_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 read_limit = 3 [json_name = "readLimit"];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.read_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReadRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.bytestream.ReadRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string resource_name = 1 [json_name = "resourceName"];
  if (!this->_internal_resource_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_resource_name().data(), static_cast<int>(this->_internal_resource_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.bytestream.ReadRequest.resource_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_resource_name(), target);
  }

  // int64 read_offset = 2 [json_name = "readOffset"];
  if (this->_internal_read_offset() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_read_offset(), target);
  }

  // int64 read_limit = 3 [json_name = "readLimit"];
  if (this->_internal_read_limit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_read_limit(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.bytestream.ReadRequest)
  return target;
}

size_t ReadRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.bytestream.ReadRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string resource_name = 1 [json_name = "resourceName"];
  if (!this->_internal_resource_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_resource_name());
  }

  // int64 read_offset = 2 [json_name = "readOffset"];
  if (this->_internal_read_offset() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_read_offset());
  }

  // int64 read_limit = 3 [json_name = "readLimit"];
  if (this->_internal_read_limit() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_read_limit());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReadRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ReadRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReadRequest::GetClassData() const { return &_class_data_; }


void ReadRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ReadRequest*>(&to_msg);
  auto& from = static_cast<const ReadRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.bytestream.ReadRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_resource_name().empty()) {
    _this->_internal_set_resource_name(from._internal_resource_name());
  }
  if (from._internal_read_offset() != 0) {
    _this->_internal_set_read_offset(from._internal_read_offset());
  }
  if (from._internal_read_limit() != 0) {
    _this->_internal_set_read_limit(from._internal_read_limit());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReadRequest::CopyFrom(const ReadRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.bytestream.ReadRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadRequest::IsInitialized() const {
  return true;
}

void ReadRequest::InternalSwap(ReadRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.resource_name_, lhs_arena,
      &other->_impl_.resource_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReadRequest, _impl_.read_limit_)
      + sizeof(ReadRequest::_impl_.read_limit_)
      - PROTOBUF_FIELD_OFFSET(ReadRequest, _impl_.read_offset_)>(
          reinterpret_cast<char*>(&_impl_.read_offset_),
          reinterpret_cast<char*>(&other->_impl_.read_offset_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReadRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2fbytestream_2fbytestream_2eproto_getter, &descriptor_table_google_2fbytestream_2fbytestream_2eproto_once,
      file_level_metadata_google_2fbytestream_2fbytestream_2eproto[0]);
}

// ===================================================================

class ReadResponse::_Internal {
 public:
};

ReadResponse::ReadResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.bytestream.ReadResponse)
}
ReadResponse::ReadResponse(const ReadResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ReadResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:google.bytestream.ReadResponse)
}

inline void ReadResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ReadResponse::~ReadResponse() {
  // @@protoc_insertion_point(destructor:google.bytestream.ReadResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ReadResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.Destroy();
}

void ReadResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ReadResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:google.bytestream.ReadResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReadResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes data = 10 [json_name = "data"];
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReadResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.bytestream.ReadResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes data = 10 [json_name = "data"];
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        10, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.bytestream.ReadResponse)
  return target;
}

size_t ReadResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.bytestream.ReadResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 10 [json_name = "data"];
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReadResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ReadResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReadResponse::GetClassData() const { return &_class_data_; }


void ReadResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ReadResponse*>(&to_msg);
  auto& from = static_cast<const ReadResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.bytestream.ReadResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReadResponse::CopyFrom(const ReadResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.bytestream.ReadResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadResponse::IsInitialized() const {
  return true;
}

void ReadResponse::InternalSwap(ReadResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata ReadResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2fbytestream_2fbytestream_2eproto_getter, &descriptor_table_google_2fbytestream_2fbytestream_2eproto_once,
      file_level_metadata_google_2fbytestream_2fbytestream_2eproto[1]);
}

// ===================================================================

class WriteRequest::_Internal {
 public:
};

WriteRequest::WriteRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.bytestream.WriteRequest)
}
WriteRequest::WriteRequest(const WriteRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  WriteRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_name_){}
    , decltype(_impl_.data_){}
    , decltype(_impl_.write_offset_){}
    , decltype(_impl_.finish_write_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.resource_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.resource_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_resource_name().empty()) {
    _this->_impl_.resource_name_.Set(from._internal_resource_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.write_offset_, &from._impl_.write_offset_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.finish_write_) -
    reinterpret_cast<char*>(&_impl_.write_offset_)) + sizeof(_impl_.finish_write_));
  // @@protoc_insertion_point(copy_constructor:google.bytestream.WriteRequest)
}

inline void WriteRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_name_){}
    , decltype(_impl_.data_){}
    , decltype(_impl_.write_offset_){int64_t{0}}
    , decltype(_impl_.finish_write_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.resource_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.resource_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

WriteRequest::~WriteRequest() {
  // @@protoc_insertion_point(destructor:google.bytestream.WriteRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void WriteRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.resource_name_.Destroy();
  _impl_.data_.Destroy();
}

void WriteRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void WriteRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:google.bytestream.WriteRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.resource_name_.ClearToEmpty();
  _impl_.data_.ClearToEmpty();
  ::memset(&_impl_.write_offset_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.finish_write_) -
      reinterpret_cast<char*>(&_impl_.write_offset_)) + sizeof(_impl_.finish_write_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WriteRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string resource_name = 1 [json_name = "resourceName"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_resource_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "google.bytestream.WriteRequest.resource_name"));
        } else
          goto handle_unusual;
        continue;
      // int64 write_offset = 2 [json_name = "writeOffset"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.write_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool finish_write = 3 [json_name = "finishWrite"];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.finish_write_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes data = 10 [json_name = "data"];
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* WriteRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.bytestream.WriteRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string resource_name = 1 [json_name = "resourceName"];
  if (!this->_internal_resource_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_resource_name().data(), static_cast<int>(this->_internal_resource_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.bytestream.WriteRequest.resource_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_resource_name(), target);
  }

  // int64 write_offset = 2 [json_name = "writeOffset"];
  if (this->_internal_write_offset() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_write_offset(), target);
  }

  // bool finish_write = 3 [json_name = "finishWrite"];
  if (this->_internal_finish_write() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_finish_write(), target);
  }

  // bytes data = 10 [json_name = "data"];
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        10, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.bytestream.WriteRequest)
  return target;
}

size_t WriteRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.bytestream.WriteRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string resource_name = 1 [json_name = "resourceName"];
  if (!this->_internal_resource_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_resource_name());
  }

  // bytes data = 10 [json_name = "data"];
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // int64 write_offset = 2 [json_name = "writeOffset"];
  if (this->_internal_write_offset() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_write_offset());
  }

  // bool finish_write = 3 [json_name = "finishWrite"];
  if (this->_internal_finish_write() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WriteRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    WriteRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WriteRequest::GetClassData() const { return &_class_data_; }


void WriteRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<WriteRequest*>(&to_msg);
  auto& from = static_cast<const WriteRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.bytestream.WriteRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_resource_name().empty()) {
    _this->_internal_set_resource_name(from._internal_resource_name());
  }
  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_write_offset() != 0) {
    _this->_internal_set_write_offset(from._internal_write_offset());
  }
  if (from._internal_finish_write() != 0) {
    _this->_internal_set_finish_write(from._internal_finish_write());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void WriteRequest::CopyFrom(const WriteRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.bytestream.WriteRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WriteRequest::IsInitialized() const {
  return true;
}

void WriteRequest::InternalSwap(WriteRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.resource_name_, lhs_arena,
      &other->_impl_.resource_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WriteRequest, _impl_.finish_write_)
      + sizeof(WriteRequest::_impl_.finish_write_)
      - PROTOBUF_FIELD_OFFSET(WriteRequest, _impl_.write_offset_)>(
          reinterpret_cast<char*>(&_impl_.write_offset_),
          reinterpret_cast<char*>(&other->_impl_.write_offset_));
}

::PROTOBUF_NAMESPACE_ID::Metadata WriteRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2fbytestream_2fbytestream_2eproto_getter, &descriptor_table_google_2fbytestream_2fbytestream_2eproto_once,
      file_level_metadata_google_2fbytestream_2fbytestream_2eproto[2]);
}

// ===================================================================

class WriteResponse::_Internal {
 public:
};

WriteResponse::WriteResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.bytestream.WriteResponse)
}
WriteResponse::WriteResponse(const WriteResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  WriteResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.committed_size_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.committed_size_ = from._impl_.committed_size_;
  // @@protoc_insertion_point(copy_constructor:google.bytestream.WriteResponse)
}

inline void WriteResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.committed_size_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

WriteResponse::~WriteResponse() {
  // @@protoc_insertion_point(destructor:google.bytestream.WriteResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void WriteResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void WriteResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void WriteResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:google.bytestream.WriteResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.committed_size_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WriteResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 committed_size = 1 [json_name = "committedSize"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.committed_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* WriteResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.bytestream.WriteResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 committed_size = 1 [json_name = "committedSize"];
  if (this->_internal_committed_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_committed_size(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.bytestream.WriteResponse)
  return target;
}

size_t WriteResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.bytestream.WriteResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 committed_size = 1 [json_name = "committedSize"];
  if (this->_internal_committed_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_committed_size());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WriteResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    WriteResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WriteResponse::GetClassData() const { return &_class_data_; }


void WriteResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<WriteResponse*>(&to_msg);
  auto& from = static_cast<const WriteResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.bytestream.WriteResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_committed_size() != 0) {
    _this->_internal_set_committed_size(from._internal_committed_size());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void WriteResponse::CopyFrom(const WriteResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.bytestream.WriteResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WriteResponse::IsInitialized() const {
  return true;
}

void WriteResponse::InternalSwap(WriteResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.committed_size_, other->_impl_.committed_size_);
}

::PROTOBUF_NAMESPACE_ID::Metadata WriteResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2fbytestream_2fbytestream_2eproto_getter, &descriptor_table_google_2fbytestream_2fbytestream_2eproto_once,
      file_level_metadata_google_2fbytestream_2fbytestream_2eproto[3]);
}

// ===================================================================

class QueryWriteStatusRequest::_Internal {
 public:
};

QueryWriteStatusRequest::QueryWriteStatusRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.bytestream.QueryWriteStatusRequest)
}
QueryWriteStatusRequest::QueryWriteStatusRequest(const QueryWriteStatusRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  QueryWriteStatusRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_name_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.resource_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.resource_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_resource_name().empty()) {
    _this->_impl_.resource_name_.Set(from._internal_resource_name(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:google.bytestream.QueryWriteStatusRequest)
}

inline void QueryWriteStatusRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_name_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.resource_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.resource_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

QueryWriteStatusRequest::~QueryWriteStatusRequest() {
  // @@protoc_insertion_point(destructor:google.bytestream.QueryWriteStatusRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void QueryWriteStatusRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.resource_name_.Destroy();
}

void QueryWriteStatusRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void QueryWriteStatusRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:google.bytestream.QueryWriteStatusRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.resource_name_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* QueryWriteStatusRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string resource_name = 1 [json_name = "resourceName"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_resource_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "google.bytestream.QueryWriteStatusRequest.resource_name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* QueryWriteStatusRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.bytestream.QueryWriteStatusRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string resource_name = 1 [json_name = "resourceName"];
  if (!this->_internal_resource_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_resource_name().data(), static_cast<int>(this->_internal_resource_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "google.bytestream.QueryWriteStatusRequest.resource_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_resource_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.bytestream.QueryWriteStatusRequest)
  return target;
}

size_t QueryWriteStatusRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.bytestream.QueryWriteStatusRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string resource_name = 1 [json_name = "resourceName"];
  if (!this->_internal_resource_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_resource_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData QueryWriteStatusRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    QueryWriteStatusRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*QueryWriteStatusRequest::GetClassData() const { return &_class_data_; }


void QueryWriteStatusRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<QueryWriteStatusRequest*>(&to_msg);
  auto& from = static_cast<const QueryWriteStatusRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.bytestream.QueryWriteStatusRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_resource_name().empty()) {
    _this->_internal_set_resource_name(from._internal_resource_name());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void QueryWriteStatusRequest::CopyFrom(const QueryWriteStatusRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.bytestream.QueryWriteStatusRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QueryWriteStatusRequest::IsInitialized() const {
  return true;
}

void QueryWriteStatusRequest::InternalSwap(QueryWriteStatusRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.resource_name_, lhs_arena,
      &other->_impl_.resource_name_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata QueryWriteStatusRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2fbytestream_2fbytestream_2eproto_getter, &descriptor_table_google_2fbytestream_2fbytestream_2eproto_once,
      file_level_metadata_google_2fbytestream_2fbytestream_2eproto[4]);
}

// ===================================================================

class QueryWriteStatusResponse::_Internal {
 public:
};

QueryWriteStatusResponse::QueryWriteStatusResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.bytestream.QueryWriteStatusResponse)
}
QueryWriteStatusResponse::QueryWriteStatusResponse(const QueryWriteStatusResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  QueryWriteStatusResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.committed_size_){}
    , decltype(_impl_.complete_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.committed_size_, &from._impl_.committed_size_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.complete_) -
    reinterpret_cast<char*>(&_impl_.committed_size_)) + sizeof(_impl_.complete_));
  // @@protoc_insertion_point(copy_constructor:google.bytestream.QueryWriteStatusResponse)
}

inline void QueryWriteStatusResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.committed_size_){int64_t{0}}
    , decltype(_impl_.complete_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

QueryWriteStatusResponse::~QueryWriteStatusResponse() {
  // @@protoc_insertion_point(destructor:google.bytestream.QueryWriteStatusResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void QueryWriteStatusResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void QueryWriteStatusResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void QueryWriteStatusResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:google.bytestream.QueryWriteStatusResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.committed_size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.complete_) -
      reinterpret_cast<char*>(&_impl_.committed_size_)) + sizeof(_impl_.complete_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* QueryWriteStatusResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 committed_size = 1 [json_name = "committedSize"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.committed_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool complete = 2 [json_name = "complete"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.complete_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* QueryWriteStatusResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.bytestream.QueryWriteStatusResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 committed_size = 1 [json_name = "committedSize"];
  if (this->_internal_committed_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_committed_size(), target);
  }

  // bool complete = 2 [json_name = "complete"];
  if (this->_internal_complete() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_complete(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.bytestream.QueryWriteStatusResponse)
  return target;
}

size_t QueryWriteStatusResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.bytestream.QueryWriteStatusResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 committed_size = 1 [json_name = "committedSize"];
  if (this->_internal_committed_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_committed_size());
  }

  // bool complete = 2 [json_name = "complete"];
  if (this->_internal_complete() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData QueryWriteStatusResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    QueryWriteStatusResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*QueryWriteStatusResponse::GetClassData() const { return &_class_data_; }


void QueryWriteStatusResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<QueryWriteStatusResponse*>(&to_msg);
  auto& from = static_cast<const QueryWriteStatusResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.bytestream.QueryWriteStatusResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_committed_size() != 0) {
    _this->_internal_set_committed_size(from._internal_committed_size());
  }
  if (from._internal_complete() != 0) {
    _this->_internal_set_complete(from._internal_complete());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void QueryWriteStatusResponse::CopyFrom(const QueryWriteStatusResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.bytestream.QueryWriteStatusResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QueryWriteStatusResponse::IsInitialized() const {
  return true;
}

void QueryWriteStatusResponse::InternalSwap(QueryWriteStatusResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(QueryWriteStatusResponse, _impl_.complete_)
      + sizeof(QueryWriteStatusResponse::_impl_.complete_)
      - PROTOBUF_FIELD_OFFSET(QueryWriteStatusResponse, _impl_.committed_size_)>(
          reinterpret_cast<char*>(&_impl_.committed_size_),
          reinterpret_cast<char*>(&other->_impl_.committed_size_));
}

::PROTOBUF_NAMESPACE_ID::Metadata QueryWriteStatusResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2fbytestream_2fbytestream_2eproto_getter, &descriptor_table_google_2fbytestream_2fbytestream_2eproto_once,
      file_level_metadata_google_2fbytestream_2fbytestream_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace bytestream
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::google::bytestream::ReadRequest*
Arena::CreateMaybeMessage< ::google::bytestream::ReadRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::bytestream::ReadRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::google::bytestream::ReadResponse*
Arena::CreateMaybeMessage< ::google::bytestream::ReadResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::bytestream::ReadResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::google::bytestream::WriteRequest*
Arena::CreateMaybeMessage< ::google::bytestream::WriteRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::bytestream::WriteRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::google::bytestream::WriteResponse*
Arena::CreateMaybeMessage< ::google::bytestream::WriteResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::bytestream::WriteResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::google::bytestream::QueryWriteStatusRequest*
Arena::CreateMaybeMessage< ::google::bytestream::QueryWriteStatusRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::bytestream::QueryWriteStatusRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::google::bytestream::QueryWriteStatusResponse*
Arena::CreateMaybeMessage< ::google::bytestream::QueryWriteStatusResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::bytestream::QueryWriteStatusResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
