// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/geo/type/viewport.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_google_2fgeo_2ftype_2fviewport_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_google_2fgeo_2ftype_2fviewport_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "google/type/latlng.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_google_2fgeo_2ftype_2fviewport_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_google_2fgeo_2ftype_2fviewport_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_google_2fgeo_2ftype_2fviewport_2eproto;
namespace google {
namespace geo {
namespace type {
class Viewport;
struct ViewportDefaultTypeInternal;
extern ViewportDefaultTypeInternal _Viewport_default_instance_;
}  // namespace type
}  // namespace geo
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
template<> ::google::geo::type::Viewport* Arena::CreateMaybeMessage<::google::geo::type::Viewport>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace google {
namespace geo {
namespace type {

// ===================================================================

class Viewport final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.geo.type.Viewport) */ {
 public:
  inline Viewport() : Viewport(nullptr) {}
  ~Viewport() override;
  explicit PROTOBUF_CONSTEXPR Viewport(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Viewport(const Viewport& from);
  Viewport(Viewport&& from) noexcept
    : Viewport() {
    *this = ::std::move(from);
  }

  inline Viewport& operator=(const Viewport& from) {
    CopyFrom(from);
    return *this;
  }
  inline Viewport& operator=(Viewport&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Viewport& default_instance() {
    return *internal_default_instance();
  }
  static inline const Viewport* internal_default_instance() {
    return reinterpret_cast<const Viewport*>(
               &_Viewport_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Viewport& a, Viewport& b) {
    a.Swap(&b);
  }
  inline void Swap(Viewport* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Viewport* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Viewport* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Viewport>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Viewport& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Viewport& from) {
    Viewport::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Viewport* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.geo.type.Viewport";
  }
  protected:
  explicit Viewport(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLowFieldNumber = 1,
    kHighFieldNumber = 2,
  };
  // .google.type.LatLng low = 1 [json_name = "low"];
  bool has_low() const;
  private:
  bool _internal_has_low() const;
  public:
  void clear_low();
  const ::google::type::LatLng& low() const;
  PROTOBUF_NODISCARD ::google::type::LatLng* release_low();
  ::google::type::LatLng* mutable_low();
  void set_allocated_low(::google::type::LatLng* low);
  private:
  const ::google::type::LatLng& _internal_low() const;
  ::google::type::LatLng* _internal_mutable_low();
  public:
  void unsafe_arena_set_allocated_low(
      ::google::type::LatLng* low);
  ::google::type::LatLng* unsafe_arena_release_low();

  // .google.type.LatLng high = 2 [json_name = "high"];
  bool has_high() const;
  private:
  bool _internal_has_high() const;
  public:
  void clear_high();
  const ::google::type::LatLng& high() const;
  PROTOBUF_NODISCARD ::google::type::LatLng* release_high();
  ::google::type::LatLng* mutable_high();
  void set_allocated_high(::google::type::LatLng* high);
  private:
  const ::google::type::LatLng& _internal_high() const;
  ::google::type::LatLng* _internal_mutable_high();
  public:
  void unsafe_arena_set_allocated_high(
      ::google::type::LatLng* high);
  ::google::type::LatLng* unsafe_arena_release_high();

  // @@protoc_insertion_point(class_scope:google.geo.type.Viewport)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::type::LatLng* low_;
    ::google::type::LatLng* high_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_google_2fgeo_2ftype_2fviewport_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Viewport

// .google.type.LatLng low = 1 [json_name = "low"];
inline bool Viewport::_internal_has_low() const {
  return this != internal_default_instance() && _impl_.low_ != nullptr;
}
inline bool Viewport::has_low() const {
  return _internal_has_low();
}
inline const ::google::type::LatLng& Viewport::_internal_low() const {
  const ::google::type::LatLng* p = _impl_.low_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::type::LatLng&>(
      ::google::type::_LatLng_default_instance_);
}
inline const ::google::type::LatLng& Viewport::low() const {
  // @@protoc_insertion_point(field_get:google.geo.type.Viewport.low)
  return _internal_low();
}
inline void Viewport::unsafe_arena_set_allocated_low(
    ::google::type::LatLng* low) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.low_);
  }
  _impl_.low_ = low;
  if (low) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.geo.type.Viewport.low)
}
inline ::google::type::LatLng* Viewport::release_low() {
  
  ::google::type::LatLng* temp = _impl_.low_;
  _impl_.low_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::google::type::LatLng* Viewport::unsafe_arena_release_low() {
  // @@protoc_insertion_point(field_release:google.geo.type.Viewport.low)
  
  ::google::type::LatLng* temp = _impl_.low_;
  _impl_.low_ = nullptr;
  return temp;
}
inline ::google::type::LatLng* Viewport::_internal_mutable_low() {
  
  if (_impl_.low_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::type::LatLng>(GetArenaForAllocation());
    _impl_.low_ = p;
  }
  return _impl_.low_;
}
inline ::google::type::LatLng* Viewport::mutable_low() {
  ::google::type::LatLng* _msg = _internal_mutable_low();
  // @@protoc_insertion_point(field_mutable:google.geo.type.Viewport.low)
  return _msg;
}
inline void Viewport::set_allocated_low(::google::type::LatLng* low) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.low_);
  }
  if (low) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(low));
    if (message_arena != submessage_arena) {
      low = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, low, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.low_ = low;
  // @@protoc_insertion_point(field_set_allocated:google.geo.type.Viewport.low)
}

// .google.type.LatLng high = 2 [json_name = "high"];
inline bool Viewport::_internal_has_high() const {
  return this != internal_default_instance() && _impl_.high_ != nullptr;
}
inline bool Viewport::has_high() const {
  return _internal_has_high();
}
inline const ::google::type::LatLng& Viewport::_internal_high() const {
  const ::google::type::LatLng* p = _impl_.high_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::type::LatLng&>(
      ::google::type::_LatLng_default_instance_);
}
inline const ::google::type::LatLng& Viewport::high() const {
  // @@protoc_insertion_point(field_get:google.geo.type.Viewport.high)
  return _internal_high();
}
inline void Viewport::unsafe_arena_set_allocated_high(
    ::google::type::LatLng* high) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.high_);
  }
  _impl_.high_ = high;
  if (high) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.geo.type.Viewport.high)
}
inline ::google::type::LatLng* Viewport::release_high() {
  
  ::google::type::LatLng* temp = _impl_.high_;
  _impl_.high_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::google::type::LatLng* Viewport::unsafe_arena_release_high() {
  // @@protoc_insertion_point(field_release:google.geo.type.Viewport.high)
  
  ::google::type::LatLng* temp = _impl_.high_;
  _impl_.high_ = nullptr;
  return temp;
}
inline ::google::type::LatLng* Viewport::_internal_mutable_high() {
  
  if (_impl_.high_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::type::LatLng>(GetArenaForAllocation());
    _impl_.high_ = p;
  }
  return _impl_.high_;
}
inline ::google::type::LatLng* Viewport::mutable_high() {
  ::google::type::LatLng* _msg = _internal_mutable_high();
  // @@protoc_insertion_point(field_mutable:google.geo.type.Viewport.high)
  return _msg;
}
inline void Viewport::set_allocated_high(::google::type::LatLng* high) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.high_);
  }
  if (high) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(high));
    if (message_arena != submessage_arena) {
      high = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, high, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.high_ = high;
  // @@protoc_insertion_point(field_set_allocated:google.geo.type.Viewport.high)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace type
}  // namespace geo
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_google_2fgeo_2ftype_2fviewport_2eproto
