// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/geo/type/viewport.proto

#include "google/geo/type/viewport.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace google {
namespace geo {
namespace type {
PROTOBUF_CONSTEXPR Viewport::Viewport(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.low_)*/nullptr
  , /*decltype(_impl_.high_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ViewportDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ViewportDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ViewportDefaultTypeInternal() {}
  union {
    Viewport _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ViewportDefaultTypeInternal _Viewport_default_instance_;
}  // namespace type
}  // namespace geo
}  // namespace google
static ::_pb::Metadata file_level_metadata_google_2fgeo_2ftype_2fviewport_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_google_2fgeo_2ftype_2fviewport_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_google_2fgeo_2ftype_2fviewport_2eproto = nullptr;

const uint32_t TableStruct_google_2fgeo_2ftype_2fviewport_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::google::geo::type::Viewport, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::google::geo::type::Viewport, _impl_.low_),
  PROTOBUF_FIELD_OFFSET(::google::geo::type::Viewport, _impl_.high_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::google::geo::type::Viewport)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::google::geo::type::_Viewport_default_instance_._instance,
};

const char descriptor_table_protodef_google_2fgeo_2ftype_2fviewport_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036google/geo/type/viewport.proto\022\017google"
  ".geo.type\032\030google/type/latlng.proto\"Z\n\010V"
  "iewport\022%\n\003low\030\001 \001(\0132\023.google.type.LatLn"
  "gR\003low\022\'\n\004high\030\002 \001(\0132\023.google.type.LatLn"
  "gR\004highB\304\001\n\023com.google.geo.typeB\rViewpor"
  "tProtoP\001Z@google.golang.org/genproto/goo"
  "gleapis/geo/type/viewport;viewport\242\002\003GGT"
  "\252\002\017Google.Geo.Type\312\002\017Google\\Geo\\Type\342\002\033G"
  "oogle\\Geo\\Type\\GPBMetadata\352\002\021Google::Geo"
  "::Typeb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_google_2fgeo_2ftype_2fviewport_2eproto_deps[1] = {
  &::descriptor_table_google_2ftype_2flatlng_2eproto,
};
static ::_pbi::once_flag descriptor_table_google_2fgeo_2ftype_2fviewport_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_google_2fgeo_2ftype_2fviewport_2eproto = {
    false, false, 374, descriptor_table_protodef_google_2fgeo_2ftype_2fviewport_2eproto,
    "google/geo/type/viewport.proto",
    &descriptor_table_google_2fgeo_2ftype_2fviewport_2eproto_once, descriptor_table_google_2fgeo_2ftype_2fviewport_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_google_2fgeo_2ftype_2fviewport_2eproto::offsets,
    file_level_metadata_google_2fgeo_2ftype_2fviewport_2eproto, file_level_enum_descriptors_google_2fgeo_2ftype_2fviewport_2eproto,
    file_level_service_descriptors_google_2fgeo_2ftype_2fviewport_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_google_2fgeo_2ftype_2fviewport_2eproto_getter() {
  return &descriptor_table_google_2fgeo_2ftype_2fviewport_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_google_2fgeo_2ftype_2fviewport_2eproto(&descriptor_table_google_2fgeo_2ftype_2fviewport_2eproto);
namespace google {
namespace geo {
namespace type {

// ===================================================================

class Viewport::_Internal {
 public:
  static const ::google::type::LatLng& low(const Viewport* msg);
  static const ::google::type::LatLng& high(const Viewport* msg);
};

const ::google::type::LatLng&
Viewport::_Internal::low(const Viewport* msg) {
  return *msg->_impl_.low_;
}
const ::google::type::LatLng&
Viewport::_Internal::high(const Viewport* msg) {
  return *msg->_impl_.high_;
}
void Viewport::clear_low() {
  if (GetArenaForAllocation() == nullptr && _impl_.low_ != nullptr) {
    delete _impl_.low_;
  }
  _impl_.low_ = nullptr;
}
void Viewport::clear_high() {
  if (GetArenaForAllocation() == nullptr && _impl_.high_ != nullptr) {
    delete _impl_.high_;
  }
  _impl_.high_ = nullptr;
}
Viewport::Viewport(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:google.geo.type.Viewport)
}
Viewport::Viewport(const Viewport& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Viewport* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.low_){nullptr}
    , decltype(_impl_.high_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_low()) {
    _this->_impl_.low_ = new ::google::type::LatLng(*from._impl_.low_);
  }
  if (from._internal_has_high()) {
    _this->_impl_.high_ = new ::google::type::LatLng(*from._impl_.high_);
  }
  // @@protoc_insertion_point(copy_constructor:google.geo.type.Viewport)
}

inline void Viewport::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.low_){nullptr}
    , decltype(_impl_.high_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Viewport::~Viewport() {
  // @@protoc_insertion_point(destructor:google.geo.type.Viewport)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Viewport::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.low_;
  if (this != internal_default_instance()) delete _impl_.high_;
}

void Viewport::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Viewport::Clear() {
// @@protoc_insertion_point(message_clear_start:google.geo.type.Viewport)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.low_ != nullptr) {
    delete _impl_.low_;
  }
  _impl_.low_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.high_ != nullptr) {
    delete _impl_.high_;
  }
  _impl_.high_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Viewport::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .google.type.LatLng low = 1 [json_name = "low"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_low(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .google.type.LatLng high = 2 [json_name = "high"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_high(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Viewport::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.geo.type.Viewport)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.type.LatLng low = 1 [json_name = "low"];
  if (this->_internal_has_low()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::low(this),
        _Internal::low(this).GetCachedSize(), target, stream);
  }

  // .google.type.LatLng high = 2 [json_name = "high"];
  if (this->_internal_has_high()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::high(this),
        _Internal::high(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.geo.type.Viewport)
  return target;
}

size_t Viewport::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.geo.type.Viewport)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.type.LatLng low = 1 [json_name = "low"];
  if (this->_internal_has_low()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.low_);
  }

  // .google.type.LatLng high = 2 [json_name = "high"];
  if (this->_internal_has_high()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.high_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Viewport::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Viewport::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Viewport::GetClassData() const { return &_class_data_; }


void Viewport::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Viewport*>(&to_msg);
  auto& from = static_cast<const Viewport&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.geo.type.Viewport)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_low()) {
    _this->_internal_mutable_low()->::google::type::LatLng::MergeFrom(
        from._internal_low());
  }
  if (from._internal_has_high()) {
    _this->_internal_mutable_high()->::google::type::LatLng::MergeFrom(
        from._internal_high());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Viewport::CopyFrom(const Viewport& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.geo.type.Viewport)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Viewport::IsInitialized() const {
  return true;
}

void Viewport::InternalSwap(Viewport* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Viewport, _impl_.high_)
      + sizeof(Viewport::_impl_.high_)
      - PROTOBUF_FIELD_OFFSET(Viewport, _impl_.low_)>(
          reinterpret_cast<char*>(&_impl_.low_),
          reinterpret_cast<char*>(&other->_impl_.low_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Viewport::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2fgeo_2ftype_2fviewport_2eproto_getter, &descriptor_table_google_2fgeo_2ftype_2fviewport_2eproto_once,
      file_level_metadata_google_2fgeo_2ftype_2fviewport_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace type
}  // namespace geo
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::google::geo::type::Viewport*
Arena::CreateMaybeMessage< ::google::geo::type::Viewport >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::geo::type::Viewport >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
